import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const rootDir = process.cwd()
const routeDir = path.join(rootDir, 'src', 'app', '(frontend)', 'assets-preview')
const pagePath = path.join(routeDir, 'page.tsx')
const clientPath = path.join(routeDir, 'AssetsPreviewClient.tsx')
const dataPath = path.join(routeDir, 'assetsPreviewData.ts')
const cssPath = path.join(routeDir, 'page.module.css')
const assetsRoutePath = path.join(rootDir, 'src', 'app', '(frontend)', 'assets', 'page.tsx')
const assetsDataPath = path.join(rootDir, 'src', 'app', '(frontend)', 'assets', '_lib', 'assetsData.ts')
const publicNavigationPath = path.join(rootDir, 'src', 'lib', 'publicNavigation.ts')

test('assets preview route is UI-only and uses the asset-center frame', () => {
  for (const filePath of [pagePath, clientPath, dataPath, cssPath, assetsRoutePath, assetsDataPath, publicNavigationPath]) {
    assert.equal(existsSync(filePath), true, `${path.basename(filePath)} should exist`)
  }

  const pageSource = readFileSync(pagePath, 'utf8')
  const clientSource = readFileSync(clientPath, 'utf8')
  const dataSource = readFileSync(dataPath, 'utf8')
  const cssSource = readFileSync(cssPath, 'utf8')
  const assetsRouteSource = readFileSync(assetsRoutePath, 'utf8')
  const assetsDataSource = readFileSync(assetsDataPath, 'utf8')
  const publicNavigationSource = readFileSync(publicNavigationPath, 'utf8')

  assert.match(pageSource, /AssetsPreviewClient/)
  assert.match(clientSource, /LineFrame/)
  assert.doesNotMatch(clientSource, /BorderComboFrame2/)
  assert.match(clientSource, /InspirationGridCard/)
  assert.match(clientSource, /home-test\/inspiration-grid/)
  assert.match(clientSource, /initialData/)
  assert.match(clientSource, /publicNavigationItems/)
  assert.doesNotMatch(clientSource, /cardStyles/)
  assert.doesNotMatch(clientSource, /ButtonBoxFrame/)
  assert.match(clientSource, /className=\{styles\.assetStage\}/)
  assert.match(clientSource, /className=\{styles\.mergedPanel\}/)
  assert.match(clientSource, /className=\{styles\.assetCenterFrame\}/)
  assert.match(clientSource, /contentClassName=\{styles\.assetCenterContent\}/)
  assert.doesNotMatch(clientSource, /className=\{styles\.profileLineFrame\}/)
  assert.doesNotMatch(clientSource, /className=\{styles\.assetsLineFrame\}/)
  assert.match(clientSource, /frameSize=\{96\}/)
  assert.match(clientSource, /contentPadding=\{64\}/)
  assert.doesNotMatch(clientSource, /contentPadding=\{20\}/)
  assert.doesNotMatch(clientSource, /frameSize=\{44\}/)
  assert.doesNotMatch(clientSource, /className=\{styles\.assetsFrame\}/)
  assert.match(clientSource, /<section className=\{styles\.profileHero\}/)
  assert.doesNotMatch(clientSource, /className=\{styles\.profileFrame\}/)
  assert.doesNotMatch(clientSource, /contentClassName=\{styles\.profileFrameContent\}/)
  assert.match(clientSource, /<InspirationGridCard/)
  assert.match(clientSource, /assetsPanel/)
  assert.match(cssSource, /\.assetsPanel/)
  assert.match(cssSource, /\.assetStage/)
  assert.match(cssSource, /\.assetsSection/)
  assert.match(cssSource, /\.mergedPanel/)
  assert.match(cssSource, /\.assetCenterFrame/)
  assert.match(cssSource, /\.assetCenterContent\s*{\s*background:\s*#050505/)
  assert.doesNotMatch(cssSource, /\.profileLineFrame/)
  assert.doesNotMatch(cssSource, /\.assetsLineFrame/)
  assert.doesNotMatch(cssSource, /\.profileLineContent/)
  assert.doesNotMatch(cssSource, /\.assetsLineContent/)
  assert.doesNotMatch(cssSource, /margin-top:\s*-/)
  assert.doesNotMatch(cssSource, /\.assetCardFrameContent/)
  assert.doesNotMatch(cssSource, /\.assetCardFrame/)
  assert.doesNotMatch(cssSource, /\.avatarAction/)
  assert.doesNotMatch(cssSource, /\.assetsFrame/)
  assert.doesNotMatch(cssSource, /\.profileFrame/)
  assert.doesNotMatch(cssSource, /\.profileFrameContent/)
  assert.doesNotMatch(cssSource, /height:\s*1446px/)
  assert.doesNotMatch(cssSource, /min-height:\s*1446px/)
  assert.doesNotMatch(cssSource, /inset:\s*0\s+0\s+42px\s+0/)
  assert.match(cssSource, /--assets-profile-height/)
  assert.match(cssSource, /--assets-profile-height:\s*128px/)
  assert.match(cssSource, /background-repeat:\s*repeat-x/)
  assert.match(cssSource, /background-size:\s*auto\s+100%/)
  assert.match(cssSource, /height:\s*96px/)
  assert.match(cssSource, /\.profileHero::after\s*{[\s\S]*height:\s*1px/)
  assert.doesNotMatch(cssSource, /box-shadow:\s*inset\s+0\s+0\s+0\s+1px/)
  assert.match(cssSource, /padding:\s*0\s+0\s+32px/)
  assert.match(cssSource, /--assets-grid-top/)
  assert.match(clientSource, /My Assets/)
  assert.match(clientSource, /My Collections/)
  assert.match(clientSource, /My Follows/)
  assert.match(clientSource, /Creator Assets/)
  assert.match(clientSource, /Hide Current Model/)
  assert.match(clientSource, /Delete Current Model/)
  assert.match(clientSource, /setModels/)
  assert.match(dataSource, /visibility:\s*'public'/)
  assert.match(dataSource, /visibility:\s*'private'/)
  assert.match(assetsRouteSource, /requireUser\('\/assets'\)/)
  assert.match(assetsRouteSource, /getAssetsPageData/)
  assert.match(assetsRouteSource, /initialData=\{assetsData\}/)
  assert.match(assetsDataSource, /collection:\s*'models'/)
  assert.match(assetsDataSource, /collection:\s*'model-favorites'/)
  assert.match(assetsDataSource, /collection:\s*'user-follows'/)
  assert.match(assetsDataSource, /overrideAccess:\s*false/)
  assert.match(assetsDataSource, /user:\s*currentUser/)
  assert.match(publicNavigationSource, /href:\s*'\/assets'/)
  assert.match(publicNavigationSource, /id:\s*'ASSETS'/)
  assert.doesNotMatch(clientSource, /\/api\/account\/models/)
  assert.doesNotMatch(clientSource, /\/api\/social\/models/)
  assert.doesNotMatch(clientSource, /\/api\/creators/)
})

test('assets route exists as the formal entry', () => {
  const assetsSource = readFileSync(assetsRoutePath, 'utf8')

  assert.equal(existsSync(assetsRoutePath), true)
  assert.match(assetsSource, /AssetsPreviewClient/)
  assert.match(assetsSource, /Assets \| Thorns Tavern/)
})
