import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const pagePath = 'src/app/(frontend)/test-home/page.tsx'
const homePagePath = 'src/app/(frontend)/page.tsx'
const cssPath = 'src/app/(frontend)/test-home/testHomePage.module.css'
const homeDataPath = 'src/app/(frontend)/_home/homeData.ts'
const selectableFrameCssPath = 'src/components/ui-lab/home-test/selectable-frame-row.module.css'

test('/test-home uses responsive homepage containers without whole-page scaling', async () => {
  const [pageSource, cssSource, selectableFrameCssSource] = await Promise.all([
    readFile(pagePath, 'utf8'),
    readFile(cssPath, 'utf8'),
    readFile(selectableFrameCssPath, 'utf8'),
  ])

  assert.match(pageSource, /TopNavigation/)
  assert.match(pageSource, /<AuthModalStage clipContent=\{false\} fitViewport>/)
  assert.match(pageSource, /HomeHero/)
  assert.doesNotMatch(pageSource, /Frame12877/)
  assert.match(pageSource, /getHomeData/)
  assert.match(pageSource, /featureFrameBody/)
  assert.match(pageSource, /HeroProductRibbon/)
  assert.match(pageSource, /getSupabasePreviewImageURL/)
  assert.match(pageSource, /TestHomeBundleFrame/)
  assert.match(pageSource, /TestHomeInspirationFrame/)
  assert.doesNotMatch(pageSource, /SmallButtonPair/)
  assert.doesNotMatch(pageSource, /SmallButtonTriple/)
  assert.match(pageSource, /FooterBar/)
  assert.match(pageSource, /BorderComboFrame2Variant/)
  assert.doesNotMatch(pageSource, /className=\{styles\.heroStage\}/)
  assert.match(pageSource, /className=\{styles\.heroBottomBanner\}/)
  assert.match(pageSource, /className=\{styles\.heroSecondBanner\}/)
  assert.match(pageSource, /className=\{styles\.heroThirdBanner\}/)
  assert.doesNotMatch(pageSource, /<BorderComboFrame2\s+className=\{styles\.heroSecondBanner\}/)
  assert.doesNotMatch(pageSource, /<BorderComboFrame2\s+className=\{styles\.heroThirdBanner\}/)
  assert.doesNotMatch(pageSource, /className=\{styles\.frameShell\}/)
  assert.doesNotMatch(pageSource, /HeroImageFrameStrip/)
  assert.doesNotMatch(pageSource, /BundleShelfControls/)
  assert.doesNotMatch(pageSource, /<InspirationGrid\s/)

  const interactiveSource = await readFile('src/app/(frontend)/test-home/TestHomeInteractivePanels.tsx', 'utf8')
  const homeDataSource = await readFile(homeDataPath, 'utf8')
  assert.match(interactiveSource, /"use client"/)
  assert.match(interactiveSource, /useMemo/)
  assert.match(interactiveSource, /useState/)
  assert.match(interactiveSource, /function TestHomeBundleFrame/)
  assert.match(interactiveSource, /function TestHomeInspirationFrame/)
  assert.match(interactiveSource, /BorderComboFrame2Container/)
  assert.match(interactiveSource, /header=\{/)
  assert.match(interactiveSource, /className=\{styles\.frameHeader\}/)
  assert.match(interactiveSource, /className=\{styles\.frameActions\}/)
  assert.match(interactiveSource, /SmallButtonPair/)
  assert.match(interactiveSource, /onChange=\{\(button\) => setFilter\(button === "purple" \? "hot" : "new"\)\}/)
  assert.match(interactiveSource, /SelectableFrameRow fillEmptyFrames=\{false\}/)
  assert.match(interactiveSource, /InspirationGridCard/)
  assert.match(interactiveSource, /InspirationSearchBox/)
  assert.match(interactiveSource, /InspirationPager/)
  assert.match(interactiveSource, /basePath\s*=\s*"\/test-home"/)
  assert.match(interactiveSource, /<InspirationSearchBox basePath=\{basePath\}/)
  assert.match(interactiveSource, /<InspirationPager basePath=\{basePath\}/)
  assert.match(interactiveSource, /SmallButtonTriple/)
  assert.match(interactiveSource, /const nextFilter = filterByButtonId\[button\]/)
  assert.match(interactiveSource, /current === nextFilter \? "all" : nextFilter/)
  assert.match(interactiveSource, /filteredItems/)
  assert.match(interactiveSource, /contentItems\.slice\(offset,\s*offset\s*\+\s*3\)/)
  assert.doesNotMatch(interactiveSource, /contentItems\.slice\(offset,\s*offset\s*\+\s*2\)/)
  assert.match(homeDataSource, /bio:\s*navUser\.bio/)
  assert.match(homeDataSource, /creditsBalance:\s*navUser\.creditsBalance/)
  assert.match(homeDataSource, /followersCount:\s*navUser\.followersCount/)
  assert.match(homeDataSource, /followingCount:\s*navUser\.followingCount/)
  assert.match(homeDataSource, /modelsCount:\s*navUser\.modelsCount/)
  assert.match(homeDataSource, /stripGeneratedTestTitlePrefix\(bundle\.title\)/)
  assert.match(homeDataSource, /stripGeneratedTestTitlePrefix\(title\)/)

  const homePageSource = await readFile(homePagePath, 'utf8')
  assert.match(homePageSource, /TopNavigation/)
  assert.match(homePageSource, /<AuthModalStage clipContent=\{false\} fitViewport>/)
  assert.match(homePageSource, /user=\{data\.navUser\}/)
  assert.match(homePageSource, /TestHomeBundleFrame/)
  assert.match(homePageSource, /TestHomeInspirationFrame/)
  assert.doesNotMatch(homePageSource, /<BorderComboFrame2\s+className=\{styles\.heroSecondBanner\}/)
  assert.doesNotMatch(homePageSource, /<BorderComboFrame2\s+className=\{styles\.heroThirdBanner\}/)
  assert.doesNotMatch(homePageSource, /TopNavBar/)
  assert.doesNotMatch(homePageSource, /ProfileMenuReferencePreview/)

  assert.match(cssSource, /\.page\s*\{[\s\S]*background:\s*#181818/)
  assert.match(cssSource, /\.footerMount\s*\{[\s\S]*background:\s*#181818[\s\S]*padding:\s*0/)
  assert.match(cssSource, /\.footerMount :global\(footer > div\)\s*\{[\s\S]*min-height:\s*176px/)
  assert.match(cssSource, /--frame-gutter:\s*32px/)
  assert.match(cssSource, /\.framedSection\s*\{[\s\S]*padding-inline:\s*var\(--frame-gutter\)/)
  assert.match(cssSource, /\.boundTopNavigation(?:\.boundTopNavigation)?\s*\{[^}]*position:\s*fixed/)
  assert.match(cssSource, /\.boundTopNavigation(?:\.boundTopNavigation)?\s*\{[^}]*top:\s*0/)
  assert.doesNotMatch(cssSource, /\.boundTopNavigation(?:\.boundTopNavigation)?\s*\{[^}]*position:\s*absolute/)
  assert.doesNotMatch(cssSource, /\.boundTopNavigation(?:\.boundTopNavigation)?\s*\{[^}]*position:\s*sticky/)
  assert.doesNotMatch(cssSource, /Pixso-/)
  assert.doesNotMatch(cssSource, /\.heroStage/)
  assert.match(cssSource, /\.heroBottomBanner\s*\{[\s\S]*height:\s*332px[\s\S]*margin-top:\s*6px/)
  assert.match(cssSource, /\.heroBottomBanner > :global\(\[class\*="content"\]\)\s*\{[\s\S]*padding:\s*0/)
  assert.match(cssSource, /\.heroSecondBanner\s*\{[\s\S]*--frame-control-right-bleed:\s*-19px/)
  assert.match(cssSource, /\.featureFrameBody\s*\{[\s\S]*display:\s*grid[\s\S]*grid-template-columns:\s*minmax\(0,\s*700fr\)\s+minmax\(0,\s*360fr\)\s+minmax\(0,\s*360fr\)\s+minmax\(0,\s*360fr\)/)
  assert.doesNotMatch(cssSource, /grid-template-columns:[^;]*0\.94fr/)
  assert.doesNotMatch(cssSource, /grid-template-columns:\s*700px\s+360px\s+360px\s+340px/)
  assert.match(cssSource, /\.featureFrameBody\s*\{[\s\S]*height:\s*268px[\s\S]*left:\s*24px[\s\S]*top:\s*32px[\s\S]*transform:\s*none[\s\S]*width:\s*min\(1800px,\s*calc\(100%\s*-\s*54px\)\)/)
  assert.match(cssSource, /\.featureFrameBody\s*\{[\s\S]*overflow:\s*hidden/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.featureFrameBody\s*\{[\s\S]*justify-content:\s*start/)
  assert.doesNotMatch(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.heroBottomBanner,\s*\.heroSecondBanner,\s*\.heroThirdBanner\s*\{[\s\S]*height:\s*auto/)
  assert.doesNotMatch(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.heroSecondBanner,\s*\.heroThirdBanner\s*\{[\s\S]*height:\s*auto/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.heroThirdBanner\s*\{[\s\S]*height:\s*auto/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.heroThirdBanner \.frameHeader\s*\{[\s\S]*height:\s*112px/)
  assert.match(cssSource, /\.heroSecondBanner\.heroSecondBanner\s*\{[\s\S]*--upper-height:\s*calc\(72px\s*-\s*var\(--top-height\)\s*-\s*\(var\(--middle-height\)\s*\/\s*2\)\)/)
  assert.match(cssSource, /\.heroThirdBanner\.heroThirdBanner\s*\{[\s\S]*--upper-height:\s*calc\(112px\s*-\s*var\(--top-height\)\s*-\s*\(var\(--middle-height\)\s*\/\s*2\)\)/)
  assert.match(cssSource, /\.heroSecondBanner\s*\{[\s\S]*height:\s*434px[\s\S]*margin-top:\s*33px/)
  assert.match(cssSource, /\.heroThirdBanner\s*\{[\s\S]*height:\s*auto[\s\S]*margin-top:\s*33px[\s\S]*min-height:\s*760px/)
  assert.doesNotMatch(cssSource, /\.heroThirdBanner\s*\{[\s\S]*height:\s*2226px/)
  assert.match(cssSource, /\.heroSecondBanner \.frameHeader\s*\{[\s\S]*height:\s*72px/)
  assert.match(cssSource, /\.bundleFrameBody\s*\{[^}]*align-items:\s*center/)
  assert.match(cssSource, /\.bundleFrameBody\s*\{[^}]*display:\s*flex/)
  assert.match(cssSource, /\.bundleFrameBody\s*\{[^}]*height:\s*300px/)
  assert.match(cssSource, /\.bundleFrameBody\s*\{[^}]*margin-top:\s*-1px/)
  assert.match(cssSource, /\.bundleFrameBody\s*\{[^}]*padding:\s*0/)
  assert.match(cssSource, /\.inspirationFrameBody\s*\{[^}]*position:\s*relative/)
  assert.match(cssSource, /\.inspirationFrameBody\s*\{[^}]*padding:\s*21px\s+0\s+0/)
  const desktopCssSource = cssSource.split('@media (max-width: 1919px)')[0] ?? cssSource

  assert.match(cssSource, /\.heroThirdBanner\s*\{[\s\S]*--frame-control-right-bleed:\s*-19px/)
  assert.match(desktopCssSource, /\.inspirationSearchMount\s*\{[^}]*left:\s*auto/)
  assert.match(desktopCssSource, /\.inspirationSearchMount\s*\{[^}]*margin:\s*0\s+var\(--frame-control-right-bleed\)\s+min\(1\.354vw,\s*26px\)\s+auto/)
  assert.match(desktopCssSource, /\.inspirationSearchMount\s*\{[^}]*transform:\s*none/)
  assert.match(desktopCssSource, /\.inspirationSearchMount\s*\{[^}]*width:\s*min\(48vw,\s*calc\(100%\s*-\s*46px\)\)/)
  assert.match(desktopCssSource, /\.inspirationSearchMount :global\(\[class\*="toolbar"\]\)\s*\{[\s\S]*margin-left:\s*auto[\s\S]*width:\s*100%[\s\S]*justify-content:\s*flex-end/)
  assert.match(cssSource, /\.featureFrameCard\s*\{[\s\S]*height:\s*100%[\s\S]*width:\s*auto/)
  assert.match(cssSource, /\.featureRibbon\s*\{[\s\S]*left:\s*36px[\s\S]*top:\s*-5px/)
  assert.match(cssSource, /\.featureLargeCard\s*\{[\s\S]*width:\s*auto/)
  assert.match(cssSource, /\.featureSmallCard\s*\{[\s\S]*width:\s*auto/)
  assert.match(cssSource, /\.featureLastCard\s*\{[\s\S]*width:\s*auto/)
  assert.match(cssSource, /@media \(max-width:\s*1187px\)[\s\S]*\.featureSmallCard\s*\{[\s\S]*display:\s*block/)
  assert.match(cssSource, /\.frameHeader\s*\{[\s\S]*grid-template-columns:\s*58px\s+240px\s+minmax\(0,\s*1fr\)\s+auto/)
  assert.match(cssSource, /\.frameHeader\s*\{[\s\S]*padding:\s*22px\s+0\s+0\s+0/)
  assert.match(cssSource, /\.frameLogo\s*\{[\s\S]*margin-left:\s*-4px[\s\S]*margin-top:\s*4px/)
  assert.match(cssSource, /\.frameDivider\s*\{[\s\S]*margin-left:\s*-9px[\s\S]*margin-top:\s*26px/)
  assert.match(cssSource, /\.frameActions\s*\{[\s\S]*display:\s*flex[\s\S]*gap:\s*16px[\s\S]*margin-top:\s*1\.5px[\s\S]*transform:\s*translateX\(18px\)/)
  assert.match(cssSource, /\.heroThirdBanner \.frameTitlePlate\s*\{[\s\S]*margin-left:\s*4px/)
  assert.match(cssSource, /\.heroThirdBanner \.frameDivider\s*\{[\s\S]*margin-left:\s*-13px/)
  assert.match(desktopCssSource, /\.heroThirdBanner \.frameActions\s*\{[\s\S]*justify-content:\s*flex-end[\s\S]*transform:\s*translateX\(19px\)[\s\S]*width:\s*412px/)
  assert.match(cssSource, /\.frameMoreAction\s*\{[^}]*width:\s*110px[\s\S]*height:\s*58px/)
  assert.match(cssSource, /\.frameMoreAction button\s*\{[^}]*height:\s*58px[\s\S]*width:\s*110px/)
  assert.doesNotMatch(cssSource, /\.frameMoreAction \[data-medium-action-label\]\s*\{[\s\S]*font-size:\s*12px/)
  assert.match(cssSource, /\.bundleFrameBody :global\(\[aria-label="Selectable frame row"\]\)\s*\{[\s\S]*display:\s*block/)
  assert.match(cssSource, /\.bundleFrameBody :global\(\[aria-label="Selectable frame row"\]\)\s*\{[\s\S]*--arrow-offset:\s*16px[\s\S]*--arrow-width:\s*48px[\s\S]*--frame-height:\s*300px[\s\S]*--frame-gap:\s*12px[\s\S]*--track-offset:\s*calc\(var\(--arrow-offset\)\s*\+\s*var\(--arrow-width\)\s*\+\s*var\(--frame-gap\)\)/)
  assert.match(cssSource, /\.bundleFrameBody :global\(\[aria-label="Selectable frame row"\]\)\s*\{[\s\S]*--frame-width:\s*408px/)
  assert.match(selectableFrameCssSource, /\.row\s*\{[\s\S]*--frame-width:\s*408px/)
  assert.doesNotMatch(cssSource, /--frame-width:\s*clamp\(/)
  assert.doesNotMatch(cssSource, /--frame-height:\s*calc\(var\(--frame-width\)\s*\*\s*300\s*\/\s*408\)/)
  assert.doesNotMatch(selectableFrameCssSource, /--frame-width:\s*min\(/)
  assert.match(cssSource, /\.bundleFrameBody :global\(\[aria-label="Selectable frame row"\]\)\s*\{[\s\S]*flex:\s*0\s+0\s+calc\(100%\s*\+\s*66px\)[\s\S]*position:\s*relative[\s\S]*left:\s*-32px[\s\S]*top:\s*auto[\s\S]*overflow:\s*hidden[\s\S]*transform:\s*none[\s\S]*width:\s*calc\(100%\s*\+\s*66px\)/)
  assert.match(cssSource, /\.bundleFrameBody :global\(\[data-selectable-frame-track\]\)\s*\{[\s\S]*display:\s*flex[\s\S]*gap:\s*var\(--frame-gap\)[\s\S]*left:\s*var\(--track-offset\)[\s\S]*overflow:\s*hidden[\s\S]*position:\s*absolute[\s\S]*right:\s*var\(--track-offset\)/)
  assert.match(selectableFrameCssSource, /\.cardsTrack\s*\{[\s\S]*transform:\s*translateY\(6px\)/)
  assert.match(cssSource, /\.bundleFrameBody :global\(\[data-selectable-frame-track\]\s*>\s*button\[aria-pressed\]\)\s*\{[\s\S]*flex:\s*0\s+0\s+var\(--frame-width\)[\s\S]*width:\s*var\(--frame-width\)[\s\S]*height:\s*var\(--frame-height\)/)
  assert.match(cssSource, /@media \(max-width:\s*1899px\)\s*\{[\s\S]*\.heroSecondBanner :global\(\[data-selectable-frame-track\]\s*>\s*button\[aria-pressed\]:nth-last-child\(2\):not\(:last-child\)\)\s*\{[\s\S]*display:\s*none/)
  assert.match(cssSource, /@media \(max-width:\s*1479px\)\s*\{[\s\S]*\.heroSecondBanner :global\(\[data-selectable-frame-track\]\s*>\s*button\[aria-pressed\]:nth-last-child\(3\):not\(:last-child\)\)\s*\{[\s\S]*display:\s*none/)
  assert.match(cssSource, /@media \(max-width:\s*1059px\)\s*\{[\s\S]*\.heroSecondBanner :global\(\[data-selectable-frame-track\]\s*>\s*button\[aria-pressed\]:not\(:last-child\)\)\s*\{[\s\S]*display:\s*none/)
  assert.doesNotMatch(cssSource, /@media \(max-width:\s*1719px\)[\s\S]*\.heroSecondBanner :global\(\[data-selectable-frame-track\]/)
  assert.doesNotMatch(cssSource, /@media \(max-width:\s*1295px\)[\s\S]*\.heroSecondBanner :global\(\[data-selectable-frame-track\]/)
  assert.doesNotMatch(cssSource, /@media \(max-width:\s*871px\)[\s\S]*\.heroSecondBanner :global\(\[data-selectable-frame-track\]/)
  assert.doesNotMatch(cssSource, /nth-of-type\(n\s*\+\s*4\)/)
  assert.match(selectableFrameCssSource, /\.frame\s*\{[\s\S]*border-radius:\s*8px[\s\S]*overflow:\s*hidden/)
  assert.match(selectableFrameCssSource, /\.frameImage\s*\{[\s\S]*border-radius:\s*inherit/)
  assert.match(homeDataSource, /imageSrc:\s*['"]\/ui\/frames\/allfollowed\.png['"]/)
  assert.doesNotMatch(interactiveSource, /isMoreFrame|moreActionLabel|morePanel/)
  assert.doesNotMatch(selectableFrameCssSource, /\.more(?:Frame|Panel|Title|Subtitle|Action|ActionLabel)\b/)
  assert.doesNotMatch(selectableFrameCssSource, /button-purple-wide@2x\.png/)
  assert.doesNotMatch(selectableFrameCssSource, /\.frame\[aria-pressed="true"\]\s*\{[^}]*box-shadow:/)
  assert.doesNotMatch(selectableFrameCssSource, /rgba\(94,\s*160,\s*255/)
  assert.match(cssSource, /\.bundleFrameBody :global\(\[aria-label="Previous image"\]\),\s*\.bundleFrameBody :global\(\[aria-label="Next image"\]\)\s*\{[\s\S]*display:\s*block[\s\S]*position:\s*absolute[\s\S]*top:\s*0/)
  assert.match(cssSource, /\.bundleFrameBody :global\(\[aria-label="Previous image"\]\)\s*\{[\s\S]*left:\s*var\(--arrow-offset\)/)
  assert.match(cssSource, /\.bundleFrameBody :global\(\[aria-label="Next image"\]\)\s*\{[^}]*right:\s*var\(--arrow-offset\)/)
  assert.doesNotMatch(cssSource, /flex:\s*0\s+0\s+408px/)
  assert.doesNotMatch(cssSource, /left:\s*68px/)
  assert.doesNotMatch(cssSource, /right:\s*68px/)
  assert.doesNotMatch(cssSource, /padding:\s*0\s+67px/)
  assert.doesNotMatch(cssSource, /left:\s*-67px/)
  assert.doesNotMatch(cssSource, /right:\s*-67px/)
  assert.doesNotMatch(cssSource, /@media \(min-width:\s*1200px\) and \(max-width:\s*1919px\)[\s\S]*\.heroSecondBanner :global\(\[aria-label="Selectable frame row"\]\)/)
  assert.match(cssSource, /\.inspirationSearchMount\s*\{[^}]*position:\s*relative/)
  assert.match(cssSource, /\.inspirationSearchMount\s*\{[^}]*left:\s*auto/)
  assert.match(cssSource, /\.inspirationSearchMount\s*\{[^}]*transform:\s*none/)
  assert.match(cssSource, /\.inspirationSearchMount\s*\{[^}]*width:\s*min\(48vw,\s*calc\(100%\s*-\s*46px\)\)/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.inspirationFrameBody\s*\{[\s\S]*padding:\s*21px\s+0\s+0/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.inspirationSearchMount\s*\{[\s\S]*height:\s*32px[\s\S]*left:\s*auto[\s\S]*margin:\s*0\s+var\(--frame-control-right-bleed\)\s+min\(1\.354vw,\s*26px\)\s+auto[\s\S]*transform:\s*none[\s\S]*width:\s*min\(48vw,\s*calc\(100%\s*-\s*46px\)\)/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.inspirationSearchMount :global\(\[class\*="toolbar"\]\)\s*\{[\s\S]*margin-left:\s*auto[\s\S]*width:\s*100%[\s\S]*justify-content:\s*flex-end/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.inspirationGridDivider\s*\{[\s\S]*display:\s*block[\s\S]*height:\s*2px[\s\S]*left:\s*50%[\s\S]*margin:\s*0\s+auto\s+min\(2\.135vw,\s*41px\)[\s\S]*position:\s*relative[\s\S]*transform:\s*translateX\(-50%\)[\s\S]*width:\s*min\(94\.167vw,\s*calc\(100%\s*\+\s*34px\)\)/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.bottomPagerMount\s*\{[\s\S]*display:\s*flex[\s\S]*justify-content:\s*center[\s\S]*margin:\s*0[\s\S]*width:\s*100%/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.heroThirdBanner :global\(\[aria-label="Inspiration grid"\]\)\s*\{[\s\S]*--card-width:\s*274px[\s\S]*--card-height:\s*437px[\s\S]*gap:\s*min\(0\.694vw,\s*13\.333px\)\s+6px[\s\S]*width:\s*min\(92\.396vw,\s*calc\(100%\s*\+\s*34px\)\)/)
  assert.match(cssSource, /\.inspirationGridDivider\s*\{[^}]*position:\s*relative/)
  assert.match(cssSource, /\.inspirationGridDivider\s*\{[^}]*left:\s*50%/)
  assert.match(cssSource, /\.inspirationGridDivider\s*\{[^}]*transform:\s*translateX\(-50%\)/)
  assert.match(cssSource, /\.inspirationGridDivider\s*\{[^}]*width:\s*min\(94\.167vw,\s*calc\(100%\s*\+\s*34px\)\)/)
  assert.match(cssSource, /\.inspirationGrid\s*\{[^}]*position:\s*relative/)
  assert.match(cssSource, /\.inspirationGrid\s*\{[^}]*top:\s*auto/)
  assert.match(cssSource, /\.inspirationGrid\s*\{[\s\S]*grid-template-columns:\s*repeat\(6,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(cssSource, /\.inspirationGrid\s*\{[\s\S]*justify-items:\s*center/)
  assert.doesNotMatch(cssSource, /\.heroThirdBanner :global\(\[aria-label="Inspiration grid"\]\)\s*\{[^}]*grid-template-columns:\s*repeat\(auto-fit,/)
  assert.match(cssSource, /\.heroThirdBanner :global\(\[aria-label="Inspiration grid"\]\)\s*\{[\s\S]*grid-template-columns:\s*repeat\(6,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(cssSource, /@media \(max-width:\s*1679px\)\s*\{[\s\S]*\.heroThirdBanner :global\(\[aria-label="Inspiration grid"\]\)\s*\{[\s\S]*grid-template-columns:\s*repeat\(5,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(cssSource, /@media \(max-width:\s*1399px\)\s*\{[\s\S]*\.heroThirdBanner :global\(\[aria-label="Inspiration grid"\]\)\s*\{[\s\S]*grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\)/)
  assert.doesNotMatch(cssSource, /--compact-six-card-width/)
  assert.doesNotMatch(cssSource, /--standard-six-card-width/)
  assert.doesNotMatch(cssSource, /--card-width:\s*var\(--compact-six-card-width\)/)
  assert.doesNotMatch(cssSource, /--card-width:\s*var\(--standard-six-card-width\)/)
  assert.doesNotMatch(cssSource, /grid-template-columns:\s*repeat\(auto-fit,\s*minmax\([^)]*1fr/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*--frame-gutter:\s*8px/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.heroSecondBanner :global\(\[data-selectable-frame-track\]\s*>\s*button\[aria-pressed\]:not\(:last-child\)\)\s*\{[\s\S]*display:\s*none/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.heroSecondBanner :global\(\[data-selectable-frame-track\]\)\s*\{[\s\S]*left:\s*0[\s\S]*right:\s*0/)
  assert.doesNotMatch(cssSource, /gap:\s*84px\s+10px/)
  assert.doesNotMatch(cssSource, /\.frameHeader\s*\{[^}]*height:\s*276px/)
  assert.doesNotMatch(cssSource, /\.heroSecondBanner \.frameHeader\s*\{[^}]*height:\s*276px/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.frameLogo\s*\{[\s\S]*display:\s*none/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.frameTitlePlate\s*\{[\s\S]*display:\s*none/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.frameHeader\s*\{[\s\S]*margin-left:\s*calc\(-1\s*\*\s*var\(--left-width\)\)[\s\S]*width:\s*calc\(100%\s*\+\s*var\(--left-width\)\s*\+\s*var\(--right-width\)\)/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.frameActions\s*\{[\s\S]*gap:\s*8px[\s\S]*justify-self:\s*center[\s\S]*transform:\s*none/)
  assert.doesNotMatch(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.frameActions\s*\{[^}]*justify-self:\s*end/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.inspirationSearchMount\s*\{[\s\S]*height:\s*auto[\s\S]*min-height:\s*74px[\s\S]*margin-bottom:\s*18px/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.inspirationSearchMount :global\(\[class\*="pager"\]\),\s*\.inspirationSearchMount :global\(\[class\*="pageSize"\]\)\s*\{[\s\S]*margin-left:\s*0/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.heroThirdBanner \.frameActions\s*\{[\s\S]*width:\s*max-content[\s\S]*transform:\s*none/)
  assert.match(cssSource, /@media \(max-width:\s*820px\)[\s\S]*\.featureFrameBody\s*\{[\s\S]*left:\s*50%[\s\S]*transform:\s*translateX\(-50%\)/)
  assert.match(cssSource, /@media \(max-width:\s*820px\)[\s\S]*\n\s*\.frameActions\s*\{[^}]*grid-row:\s*auto/)
  assert.doesNotMatch(cssSource, /zoom:\s*calc/)
})
