import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const pagePath = 'src/app/(frontend)/test-home/page.tsx'
const homePagePath = 'src/app/(frontend)/page.tsx'
const cssPath = 'src/app/(frontend)/test-home/testHomePage.module.css'
const homeDataPath = 'src/app/(frontend)/_home/homeData.ts'

test('/test-home uses responsive homepage containers without whole-page scaling', async () => {
  const [pageSource, cssSource] = await Promise.all([
    readFile(pagePath, 'utf8'),
    readFile(cssPath, 'utf8'),
  ])

  assert.match(pageSource, /TopNavigation/)
  assert.match(pageSource, /<AuthModalStage clipContent=\{false\} fitViewport>/)
  assert.match(pageSource, /Frame12877/)
  assert.match(pageSource, /getHomeData/)
  assert.match(pageSource, /featureFrameBody/)
  assert.match(pageSource, /HeroProductRibbon/)
  assert.match(pageSource, /getSupabasePreviewImageURL/)
  assert.match(pageSource, /TestHomeBundlePanel/)
  assert.match(pageSource, /TestHomeInspirationPanel/)
  assert.doesNotMatch(pageSource, /SmallButtonPair/)
  assert.doesNotMatch(pageSource, /SmallButtonTriple/)
  assert.match(pageSource, /FooterBar/)
  assert.match(pageSource, /BorderComboFrame2/)
  assert.match(pageSource, /BorderComboFrame2Variant/)
  assert.match(pageSource, /className=\{styles\.heroStage\}/)
  assert.match(pageSource, /className=\{styles\.heroBottomBanner\}/)
  assert.match(pageSource, /className=\{styles\.heroSecondBanner\}/)
  assert.match(pageSource, /className=\{styles\.heroThirdBanner\}/)
  assert.match(pageSource, /className=\{styles\.frameShell\}/)
  assert.doesNotMatch(pageSource, /HeroImageFrameStrip/)
  assert.doesNotMatch(pageSource, /BundleShelfControls/)
  assert.doesNotMatch(pageSource, /<InspirationGrid\s/)

  const interactiveSource = await readFile('src/app/(frontend)/test-home/TestHomeInteractivePanels.tsx', 'utf8')
  const homeDataSource = await readFile(homeDataPath, 'utf8')
  assert.match(interactiveSource, /"use client"/)
  assert.match(interactiveSource, /useMemo/)
  assert.match(interactiveSource, /useState/)
  assert.match(interactiveSource, /function TestHomeBundlePanel/)
  assert.match(interactiveSource, /function TestHomeInspirationPanel/)
  assert.match(interactiveSource, /className=\{styles\.frameHeader\}/)
  assert.match(interactiveSource, /className=\{styles\.frameActions\}/)
  assert.match(interactiveSource, /SmallButtonPair/)
  assert.match(interactiveSource, /onChange=\{\(button\) => setFilter\(button === "purple" \? "hot" : "new"\)\}/)
  assert.match(interactiveSource, /SelectableFrameRow fillEmptyFrames=\{false\}/)
  assert.match(interactiveSource, /InspirationGridCard/)
  assert.match(interactiveSource, /InspirationSearchBox/)
  assert.match(interactiveSource, /InspirationPager/)
  assert.match(interactiveSource, /basePath\s*=\s*"\/test-home"/)
  assert.match(interactiveSource, /<InspirationSearchBox basePath=\{basePath\}/)
  assert.match(interactiveSource, /<InspirationPager basePath=\{basePath\}/)
  assert.match(interactiveSource, /SmallButtonTriple/)
  assert.match(interactiveSource, /const nextFilter = filterByButtonId\[button\]/)
  assert.match(interactiveSource, /current === nextFilter \? "all" : nextFilter/)
  assert.match(interactiveSource, /filteredItems/)
  assert.match(homeDataSource, /bio:\s*navUser\.bio/)
  assert.match(homeDataSource, /creditsBalance:\s*navUser\.creditsBalance/)
  assert.match(homeDataSource, /followersCount:\s*navUser\.followersCount/)
  assert.match(homeDataSource, /followingCount:\s*navUser\.followingCount/)
  assert.match(homeDataSource, /modelsCount:\s*navUser\.modelsCount/)

  const homePageSource = await readFile(homePagePath, 'utf8')
  assert.match(homePageSource, /TopNavigation/)
  assert.match(homePageSource, /<AuthModalStage clipContent=\{false\} fitViewport>/)
  assert.match(homePageSource, /user=\{data\.navUser\}/)
  assert.doesNotMatch(homePageSource, /TopNavBar/)
  assert.doesNotMatch(homePageSource, /ProfileMenuReferencePreview/)

  assert.match(cssSource, /\.page\s*\{[\s\S]*background:\s*#181818/)
  assert.match(cssSource, /\.footerMount\s*\{[\s\S]*background:\s*#181818[\s\S]*padding:\s*0/)
  assert.match(cssSource, /\.footerMount :global\(footer > div\)\s*\{[\s\S]*min-height:\s*176px/)
  assert.match(cssSource, /--frame-gutter:\s*32px/)
  assert.match(cssSource, /\.framedSection\s*\{[\s\S]*padding-inline:\s*var\(--frame-gutter\)/)
  assert.match(cssSource, /\.boundTopNavigation\s*\{[\s\S]*position:\s*absolute/)
  assert.doesNotMatch(cssSource, /\.boundTopNavigation\s*\{[\s\S]*position:\s*sticky/)
  assert.match(cssSource, /\.heroStage\s*\{[\s\S]*--hero-scale:\s*min\(1,\s*calc\(100vw\s*\/\s*1920px\)\)/)
  assert.match(cssSource, /\.heroStage\s*\{[\s\S]*height:\s*calc\(989px\s*\*\s*var\(--hero-scale\)\)[\s\S]*margin-bottom:\s*calc\(-9px\s*\*\s*var\(--hero-scale\)\)/)
  assert.match(cssSource, /\.heroStage::after\s*\{[\s\S]*background:\s*linear-gradient\(180deg,\s*rgba\(24,\s*24,\s*24,\s*0\),\s*#181818\)/)
  assert.match(cssSource, /\.heroStage\.heroStage :global\(\.scroll-container\)\s*\{[\s\S]*left:\s*50%[\s\S]*transform:\s*translateX\(-50%\)\s*scale\(var\(--hero-scale\)\)/)
  assert.match(cssSource, /\.heroStage\.heroStage :global\(\.Pixso-frame-1_2877\) > :global\(:not\(\.Pixso-vector-1_2878\)\)\s*\{[\s\S]*transform:\s*none/)
  assert.match(cssSource, /\.heroStage :global\(\.Pixso-group-1_3098\)\s*\{[\s\S]*display:\s*none/)
  assert.match(cssSource, /\.heroStage :global\(\.Pixso-group-1_3253\),\s*\.heroStage :global\(\.Pixso-group-1_3287\),\s*\.heroStage :global\(\.Pixso-group-1_3292\),\s*\.heroStage :global\(\.Pixso-home-upload-input\)\s*\{[\s\S]*pointer-events:\s*none/)
  assert.match(cssSource, /\.heroStage :global\(\.Pixso-group-1_3253\),\s*\.heroStage :global\(\.Pixso-group-1_3287\),\s*\.heroStage :global\(\.Pixso-group-1_3292\),\s*\.heroStage :global\(\.Pixso-home-upload-input\)\s*\{[\s\S]*display:\s*none/)
  assert.match(cssSource, /\.heroBottomBanner\s*\{[\s\S]*height:\s*332px[\s\S]*margin-top:\s*6px/)
  assert.match(cssSource, /\.heroBottomBanner > :global\(\[class\*="content"\]\)\s*\{[\s\S]*padding:\s*0/)
  assert.match(cssSource, /\.featureFrameBody\s*\{[\s\S]*display:\s*grid[\s\S]*grid-template-columns:\s*minmax\(0,\s*1\.94fr\)\s+minmax\(0,\s*1fr\)\s+minmax\(0,\s*1fr\)\s+minmax\(0,\s*0\.94fr\)/)
  assert.doesNotMatch(cssSource, /grid-template-columns:\s*700px\s+360px\s+360px\s+340px/)
  assert.match(cssSource, /\.featureFrameBody\s*\{[\s\S]*height:\s*280px[\s\S]*left:\s*24px[\s\S]*top:\s*26px[\s\S]*transform:\s*none[\s\S]*width:\s*min\(1828px,\s*calc\(100%\s*-\s*28px\)\)/)
  assert.match(cssSource, /\.featureFrameBody\s*\{[\s\S]*overflow:\s*hidden/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.featureFrameBody\s*\{[\s\S]*justify-content:\s*start/)
  assert.doesNotMatch(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.heroBottomBanner,\s*\.heroSecondBanner,\s*\.heroThirdBanner\s*\{[\s\S]*height:\s*auto/)
  assert.doesNotMatch(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.heroSecondBanner,\s*\.heroThirdBanner\s*\{[\s\S]*height:\s*auto/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.heroThirdBanner\s*\{[\s\S]*height:\s*auto/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.heroThirdBanner \.frameHeader\s*\{[\s\S]*height:\s*112px/)
  assert.match(cssSource, /\.heroSecondBanner\s*\{[\s\S]*height:\s*453px[\s\S]*margin-top:\s*33px/)
  assert.match(cssSource, /\.heroThirdBanner\s*\{[\s\S]*height:\s*auto[\s\S]*margin-top:\s*33px[\s\S]*min-height:\s*760px/)
  assert.doesNotMatch(cssSource, /\.heroThirdBanner\s*\{[\s\S]*height:\s*2226px/)
  assert.match(cssSource, /\.heroSecondBanner \.frameHeader\s*\{[\s\S]*height:\s*112px/)
  assert.match(cssSource, /\.bundleFrameBody\s*\{[^}]*align-items:\s*center/)
  assert.match(cssSource, /\.bundleFrameBody\s*\{[^}]*display:\s*flex/)
  assert.match(cssSource, /\.bundleFrameBody\s*\{[^}]*height:\s*332px/)
  assert.match(cssSource, /\.bundleFrameBody\s*\{[^}]*margin-top:\s*-1px/)
  assert.match(cssSource, /\.bundleFrameBody\s*\{[^}]*padding:\s*0/)
  assert.match(cssSource, /\.inspirationFrameBody\s*\{[^}]*position:\s*absolute/)
  assert.match(cssSource, /\.inspirationFrameBody\s*\{[^}]*inset:\s*0\s+0\s+42px\s+0/)
  assert.match(cssSource, /\.inspirationFrameBody\s*\{[^}]*padding:\s*0/)
  const desktopCssSource = cssSource.split('@media (max-width: 1919px)')[0] ?? cssSource
  assert.match(desktopCssSource, /\.inspirationSearchMount :global\(\[class\*="toolbar"\]\)\s*\{[\s\S]*margin-left:\s*0[\s\S]*width:\s*100%[\s\S]*justify-content:\s*flex-start/)
  assert.match(cssSource, /\.featureFrameCard\s*\{[\s\S]*height:\s*100%[\s\S]*width:\s*auto/)
  assert.match(cssSource, /\.featureRibbon\s*\{[\s\S]*left:\s*36px[\s\S]*top:\s*0/)
  assert.match(cssSource, /\.featureLargeCard\s*\{[\s\S]*width:\s*auto/)
  assert.match(cssSource, /\.featureSmallCard\s*\{[\s\S]*width:\s*auto/)
  assert.match(cssSource, /\.featureLastCard\s*\{[\s\S]*width:\s*auto/)
  assert.match(cssSource, /@media \(max-width:\s*1187px\)[\s\S]*\.featureSmallCard\s*\{[\s\S]*display:\s*block/)
  assert.match(cssSource, /\.frameHeader\s*\{[\s\S]*grid-template-columns:\s*58px\s+240px\s+minmax\(0,\s*1fr\)\s+auto/)
  assert.match(cssSource, /\.frameHeader\s*\{[\s\S]*padding:\s*22px\s+0\s+0\s+0/)
  assert.match(cssSource, /\.frameLogo\s*\{[\s\S]*margin-left:\s*-4px[\s\S]*margin-top:\s*4px/)
  assert.match(cssSource, /\.frameDivider\s*\{[\s\S]*margin-left:\s*-9px[\s\S]*margin-top:\s*26px/)
  assert.match(cssSource, /\.frameActions\s*\{[\s\S]*display:\s*flex[\s\S]*gap:\s*16px[\s\S]*margin-top:\s*1\.5px[\s\S]*transform:\s*translateX\(18px\)/)
  assert.match(cssSource, /\.heroThirdBanner \.frameTitlePlate\s*\{[\s\S]*margin-left:\s*4px/)
  assert.match(cssSource, /\.heroThirdBanner \.frameDivider\s*\{[\s\S]*margin-left:\s*-13px/)
  assert.match(cssSource, /\.heroThirdBanner \.frameActions\s*\{[\s\S]*justify-content:\s*flex-start[\s\S]*transform:\s*translateX\(19px\)[\s\S]*width:\s*412px/)
  assert.match(cssSource, /\.bundleFrameBody :global\(\[aria-label="Selectable frame row"\]\)\s*\{[\s\S]*grid-template-columns:\s*repeat\(auto-fit,\s*408px\)[\s\S]*margin:\s*0\s+auto[\s\S]*max-width:\s*1680px/)
  assert.match(cssSource, /\.bundleFrameBody :global\(\[aria-label="Selectable frame row"\]\)\s*\{[\s\S]*position:\s*relative[\s\S]*left:\s*auto[\s\S]*top:\s*auto[\s\S]*overflow:\s*visible[\s\S]*transform:\s*translateX\(1px\)/)
  assert.match(cssSource, /\.bundleFrameBody :global\(\[aria-label="Selectable frame row"\]\[data-fill-empty="false"\]\)\s*\{[\s\S]*justify-content:\s*start/)
  assert.match(cssSource, /\.bundleFrameBody :global\(\[aria-label="Previous image"\]\),\s*\.bundleFrameBody :global\(\[aria-label="Next image"\]\)\s*\{[\s\S]*display:\s*block/)
  assert.match(cssSource, /\.bundleFrameBody :global\(\[aria-label="Previous image"\]\)\s*\{[\s\S]*left:\s*-67px/)
  assert.match(cssSource, /\.bundleFrameBody :global\(\[aria-label="Next image"\]\)\s*\{[\s\S]*right:\s*-67px/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.heroSecondBanner :global\(\[aria-label="Previous image"\]\),\s*\.heroSecondBanner :global\(\[aria-label="Next image"\]\)\s*\{[\s\S]*display:\s*none/)
  assert.match(cssSource, /@media \(min-width:\s*1200px\) and \(max-width:\s*1919px\)\s*\{[\s\S]*\.heroSecondBanner :global\(\[aria-label="Selectable frame row"\]\)\s*\{[\s\S]*box-sizing:\s*border-box[\s\S]*max-width:\s*100%[\s\S]*overflow:\s*hidden[\s\S]*padding:\s*0\s+67px/)
  assert.match(cssSource, /@media \(min-width:\s*1200px\) and \(max-width:\s*1919px\)\s*\{[\s\S]*\.heroSecondBanner :global\(\[aria-label="Previous image"\]\),\s*\.heroSecondBanner :global\(\[aria-label="Next image"\]\)\s*\{[\s\S]*display:\s*block[\s\S]*transform:\s*none/)
  assert.match(cssSource, /@media \(min-width:\s*1200px\) and \(max-width:\s*1919px\)\s*\{[\s\S]*\.heroSecondBanner :global\(\[aria-label="Previous image"\]\)\s*\{[\s\S]*left:\s*0/)
  assert.match(cssSource, /@media \(min-width:\s*1200px\) and \(max-width:\s*1919px\)\s*\{[\s\S]*\.heroSecondBanner :global\(\[aria-label="Next image"\]\)\s*\{[\s\S]*right:\s*0/)
  assert.match(cssSource, /\.inspirationSearchMount\s*\{[^}]*position:\s*absolute/)
  assert.match(cssSource, /\.inspirationSearchMount\s*\{[^}]*right:\s*10px/)
  assert.match(cssSource, /\.inspirationSearchMount\s*\{[^}]*top:\s*129\.5px/)
  assert.match(cssSource, /\.inspirationSearchMount\s*\{[^}]*width:\s*min\(686px,\s*calc\(100%\s*-\s*10px\)\)/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.inspirationFrameBody\s*\{[\s\S]*padding:\s*21px\s+0\s+0/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.inspirationSearchMount\s*\{[\s\S]*height:\s*32px[\s\S]*left:\s*50%[\s\S]*margin:\s*0\s+auto\s+min\(1\.354vw,\s*26px\)[\s\S]*transform:\s*translateX\(-50%\)[\s\S]*width:\s*min\(92\.396vw,\s*calc\(100%\s*\+\s*34px\)\)/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.inspirationSearchMount :global\(\[class\*="toolbar"\]\)\s*\{[\s\S]*margin-left:\s*auto[\s\S]*width:\s*min\(48vw,\s*100%\)[\s\S]*justify-content:\s*flex-end/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.inspirationGridDivider\s*\{[\s\S]*display:\s*block[\s\S]*height:\s*2px[\s\S]*left:\s*50%[\s\S]*margin:\s*0\s+auto\s+min\(2\.135vw,\s*41px\)[\s\S]*position:\s*relative[\s\S]*transform:\s*translateX\(-50%\)[\s\S]*width:\s*min\(94\.167vw,\s*calc\(100%\s*\+\s*34px\)\)/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.bottomPagerMount\s*\{[\s\S]*display:\s*flex[\s\S]*justify-content:\s*center[\s\S]*margin:\s*0[\s\S]*width:\s*100%/)
  assert.match(cssSource, /@media \(max-width:\s*1919px\)\s*\{[\s\S]*\.heroThirdBanner :global\(\[aria-label="Inspiration grid"\]\)\s*\{[\s\S]*--card-width:\s*274px[\s\S]*--card-height:\s*437px[\s\S]*gap:\s*min\(0\.694vw,\s*13\.333px\)\s+6px[\s\S]*width:\s*min\(92\.396vw,\s*calc\(100%\s*\+\s*34px\)\)/)
  assert.match(cssSource, /\.inspirationGridDivider\s*\{[^}]*position:\s*absolute/)
  assert.match(cssSource, /\.inspirationGridDivider\s*\{[^}]*left:\s*-16px/)
  assert.match(cssSource, /\.inspirationGridDivider\s*\{[^}]*top:\s*187\.5px/)
  assert.match(cssSource, /\.inspirationGridDivider\s*\{[^}]*width:\s*calc\(100%\s*\+\s*34px\)/)
  assert.match(cssSource, /\.inspirationGrid\s*\{[^}]*position:\s*absolute/)
  assert.match(cssSource, /\.inspirationGrid\s*\{[^}]*top:\s*230\.5px/)
  assert.match(cssSource, /\.inspirationGrid\s*\{[^}]*grid-template-columns:\s*repeat\(auto-fit,\s*var\(--card-width\)\)/)
  assert.doesNotMatch(cssSource, /--compact-six-card-width/)
  assert.doesNotMatch(cssSource, /--standard-six-card-width/)
  assert.doesNotMatch(cssSource, /--card-width:\s*var\(--compact-six-card-width\)/)
  assert.doesNotMatch(cssSource, /--card-width:\s*var\(--standard-six-card-width\)/)
  assert.doesNotMatch(cssSource, /grid-template-columns:\s*repeat\(auto-fit,\s*minmax\([^)]*1fr/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*--frame-gutter:\s*8px/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.heroSecondBanner :global\(\[aria-label="Selectable frame row"\]\s*>\s*button\[aria-pressed\]:nth-of-type\(n\s*\+\s*3\)\)\s*\{[\s\S]*display:\s*none/)
  assert.doesNotMatch(cssSource, /gap:\s*84px\s+10px/)
  assert.doesNotMatch(cssSource, /\.frameHeader\s*\{[^}]*height:\s*276px/)
  assert.doesNotMatch(cssSource, /\.heroSecondBanner \.frameHeader\s*\{[^}]*height:\s*276px/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.frameLogo\s*\{[\s\S]*display:\s*none/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.frameTitlePlate\s*\{[\s\S]*display:\s*none/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.frameHeader\s*\{[\s\S]*margin-left:\s*calc\(-1\s*\*\s*var\(--left-width\)\)[\s\S]*width:\s*calc\(100%\s*\+\s*var\(--left-width\)\s*\+\s*var\(--right-width\)\)/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.frameActions\s*\{[\s\S]*gap:\s*8px[\s\S]*justify-self:\s*end[\s\S]*transform:\s*none/)
  assert.match(cssSource, /@media \(max-width:\s*520px\)[\s\S]*\.heroThirdBanner \.frameActions\s*\{[\s\S]*width:\s*max-content[\s\S]*transform:\s*none/)
  assert.match(cssSource, /@media \(max-width:\s*820px\)[\s\S]*\.featureFrameBody\s*\{[\s\S]*left:\s*50%[\s\S]*transform:\s*translateX\(-50%\)/)
  assert.doesNotMatch(cssSource, /@media \(max-width:\s*820px\)[\s\S]*\.frameActions\s*\{[^}]*grid-row:\s*2/)
  assert.doesNotMatch(cssSource, /zoom:\s*calc/)
})
