export type AssetsPreviewVisibility = 'private' | 'public'

export type AssetsPreviewCreator = {
  avatarSrc: string
  badgeLabel?: string
  bannerSrc: string
  bio: string
  displayName: string
  followersLabel: string
  id: string
  isFollowing: boolean
  modelsLabel: string
}

export type AssetsPreviewModel = {
  ageLabel: string
  createdAt: string
  creatorId: string
  favoritesLabel: string
  id: string
  imageSrc: string
  isFavorited: boolean
  isOwned: boolean
  likesLabel: string
  title: string
  tone: 'amber' | 'blue' | 'green' | 'steel'
  viewsLabel: string
  visibility: AssetsPreviewVisibility
}

export const assetsPreviewCurrentCreatorId = 'xing-mu'

export const assetsPreviewPageSizeOptions = [20, 40, 60] as const

export const assetsPreviewCreators: AssetsPreviewCreator[] = [
  {
    avatarSrc: '/ui-lab/model-detail-uicut/images/face.png',
    bannerSrc: '/ui/workbench/model-detail/sketch-assets/rail-banner-bg.webp',
    bio: 'An outstanding anime-style model creator and one-tap printable character designer.',
    displayName: 'Xing Mu',
    followersLabel: '560',
    id: assetsPreviewCurrentCreatorId,
    isFollowing: false,
    modelsLabel: '23',
  },
  {
    avatarSrc: '/ui-lab/formal-components/assets/inspiration-card/avatar-greenwood.png',
    badgeLabel: 'KICK',
    bannerSrc: '/ui/workbench/model-detail/sketch-assets/rail-banner-bg.webp',
    bio: 'Creature sculptor focused on tabletop heroes, bosses, and expressive stylized poses.',
    displayName: 'Greenwood',
    followersLabel: '2.3k',
    id: 'greenwood',
    isFollowing: true,
    modelsLabel: '56',
  },
  {
    avatarSrc: '/ui/workbench/model-detail/sketch-assets/creator-avatar.jpg',
    bannerSrc: '/ui/workbench/model-detail/sketch-assets/rail-banner-bg.webp',
    bio: 'Fantasy prop artist building compact miniatures, tavern NPCs, and printable accessories.',
    displayName: 'Nara Vale',
    followersLabel: '1.1k',
    id: 'nara-vale',
    isFollowing: true,
    modelsLabel: '18',
  },
]

export const assetsPreviewModels: AssetsPreviewModel[] = [
  {
    ageLabel: '6 Days ago',
    createdAt: '2026-06-10T15:00:00.000Z',
    creatorId: assetsPreviewCurrentCreatorId,
    favoritesLabel: '267',
    id: 'silver-lance-guard',
    imageSrc: '/ui/workbench/model-detail/sketch-assets/gallery-1.png',
    isFavorited: true,
    isOwned: true,
    likesLabel: '1.5k',
    title: 'Silver Lance Guard',
    tone: 'blue',
    viewsLabel: '320',
    visibility: 'private',
  },
  {
    ageLabel: '6 Days ago',
    createdAt: '2026-06-10T14:00:00.000Z',
    creatorId: assetsPreviewCurrentCreatorId,
    favoritesLabel: '267',
    id: 'tavern-keeper-bard',
    imageSrc: '/ui/workbench/model-detail/sketch-assets/gallery-3.png',
    isFavorited: true,
    isOwned: true,
    likesLabel: '1.5k',
    title: 'Tavern Keeper Bard',
    tone: 'amber',
    viewsLabel: '320',
    visibility: 'private',
  },
  {
    ageLabel: '5 Days ago',
    createdAt: '2026-06-10T13:00:00.000Z',
    creatorId: assetsPreviewCurrentCreatorId,
    favoritesLabel: '183',
    id: 'blue-ogre-bruiser',
    imageSrc: '/ui/workbench/model-detail/sketch-assets/gallery-2.png',
    isFavorited: false,
    isOwned: true,
    likesLabel: '904',
    title: 'Blue Arena Brute',
    tone: 'steel',
    viewsLabel: '286',
    visibility: 'public',
  },
  {
    ageLabel: '4 Days ago',
    createdAt: '2026-06-10T12:00:00.000Z',
    creatorId: assetsPreviewCurrentCreatorId,
    favoritesLabel: '211',
    id: 'market-halfling-cook',
    imageSrc: '/ui-lab/workbench-assets/monk-large.webp',
    isFavorited: true,
    isOwned: true,
    likesLabel: '821',
    title: 'Market Halfling Cook',
    tone: 'blue',
    viewsLabel: '312',
    visibility: 'private',
  },
  {
    ageLabel: '3 Days ago',
    createdAt: '2026-06-10T11:00:00.000Z',
    creatorId: assetsPreviewCurrentCreatorId,
    favoritesLabel: '142',
    id: 'court-duelist',
    imageSrc: '/ui/workbench/model-detail/sketch-assets/gallery-4.png',
    isFavorited: false,
    isOwned: true,
    likesLabel: '677',
    title: 'Court Duelist',
    tone: 'steel',
    viewsLabel: '198',
    visibility: 'public',
  },
  {
    ageLabel: '2 Days ago',
    createdAt: '2026-06-10T10:00:00.000Z',
    creatorId: assetsPreviewCurrentCreatorId,
    favoritesLabel: '91',
    id: 'monk-preview-study',
    imageSrc: '/ui/workbench/model-detail/sketch-assets/gallery-5.png',
    isFavorited: true,
    isOwned: true,
    likesLabel: '543',
    title: 'Monk Preview Study',
    tone: 'amber',
    viewsLabel: '177',
    visibility: 'public',
  },
  {
    ageLabel: '1 Day ago',
    createdAt: '2026-06-10T09:00:00.000Z',
    creatorId: assetsPreviewCurrentCreatorId,
    favoritesLabel: '267',
    id: 'frost-plate-ranger',
    imageSrc: '/ui/workbench/model-detail/sketch-assets/gallery-4.png',
    isFavorited: true,
    isOwned: true,
    likesLabel: '1.5k',
    title: 'Frost Plate Ranger',
    tone: 'blue',
    viewsLabel: '320',
    visibility: 'public',
  },
  {
    ageLabel: '1 Day ago',
    createdAt: '2026-06-10T08:00:00.000Z',
    creatorId: assetsPreviewCurrentCreatorId,
    favoritesLabel: '267',
    id: 'alehouse-guard',
    imageSrc: '/ui/workbench/model-detail/sketch-assets/gallery-5.png',
    isFavorited: true,
    isOwned: true,
    likesLabel: '1.5k',
    title: 'Alehouse Guard',
    tone: 'amber',
    viewsLabel: '320',
    visibility: 'private',
  },
  {
    ageLabel: '1 Day ago',
    createdAt: '2026-06-10T07:00:00.000Z',
    creatorId: assetsPreviewCurrentCreatorId,
    favoritesLabel: '183',
    id: 'arena-monk',
    imageSrc: '/ui-lab/workbench-assets/monk-large.webp',
    isFavorited: false,
    isOwned: true,
    likesLabel: '904',
    title: 'Arena Monk',
    tone: 'steel',
    viewsLabel: '286',
    visibility: 'public',
  },
  {
    ageLabel: '2 Days ago',
    createdAt: '2026-06-10T06:00:00.000Z',
    creatorId: assetsPreviewCurrentCreatorId,
    favoritesLabel: '211',
    id: 'wildland-captain',
    imageSrc: '/ui/workbench/model-detail/sketch-assets/gallery-3.png',
    isFavorited: true,
    isOwned: true,
    likesLabel: '821',
    title: 'Wildland Captain',
    tone: 'green',
    viewsLabel: '312',
    visibility: 'public',
  },
  {
    ageLabel: '2 Days ago',
    createdAt: '2026-06-10T05:00:00.000Z',
    creatorId: assetsPreviewCurrentCreatorId,
    favoritesLabel: '142',
    id: 'spoon-squire',
    imageSrc: '/ui/workbench/model-detail/sketch-assets/gallery-2.png',
    isFavorited: false,
    isOwned: true,
    likesLabel: '677',
    title: 'Spoon Squire',
    tone: 'steel',
    viewsLabel: '198',
    visibility: 'private',
  },
  {
    ageLabel: '2 Days ago',
    createdAt: '2026-06-10T04:00:00.000Z',
    creatorId: assetsPreviewCurrentCreatorId,
    favoritesLabel: '91',
    id: 'blue-training-monk',
    imageSrc: '/ui/workbench/model-detail/sketch-assets/gallery-1.png',
    isFavorited: true,
    isOwned: true,
    likesLabel: '543',
    title: 'Blue Training Monk',
    tone: 'blue',
    viewsLabel: '177',
    visibility: 'private',
  },
  {
    ageLabel: '1 Day ago',
    createdAt: '2026-06-10T12:30:00.000Z',
    creatorId: 'greenwood',
    favoritesLabel: '267',
    id: 'forest-vanguard',
    imageSrc: '/ui/workbench/model-detail/sketch-assets/gallery-1.png',
    isFavorited: true,
    isOwned: false,
    likesLabel: '56',
    title: 'Forest Vanguard',
    tone: 'blue',
    viewsLabel: '2.3k',
    visibility: 'public',
  },
  {
    ageLabel: '2 Days ago',
    createdAt: '2026-06-09T13:30:00.000Z',
    creatorId: 'greenwood',
    favoritesLabel: '267',
    id: 'ember-tribe-warden',
    imageSrc: '/ui/workbench/model-detail/sketch-assets/gallery-5.png',
    isFavorited: true,
    isOwned: false,
    likesLabel: '56',
    title: 'Ember Tribe Warden',
    tone: 'amber',
    viewsLabel: '2.3k',
    visibility: 'public',
  },
  {
    ageLabel: '3 Days ago',
    createdAt: '2026-06-08T12:30:00.000Z',
    creatorId: 'greenwood',
    favoritesLabel: '144',
    id: 'night-plate-rogue',
    imageSrc: '/ui/workbench/model-detail/sketch-assets/gallery-2.png',
    isFavorited: false,
    isOwned: false,
    likesLabel: '44',
    title: 'Night Plate Rogue',
    tone: 'steel',
    viewsLabel: '1.8k',
    visibility: 'public',
  },
  {
    ageLabel: '4 Days ago',
    createdAt: '2026-06-07T12:30:00.000Z',
    creatorId: 'greenwood',
    favoritesLabel: '88',
    id: 'river-stone-guardian',
    imageSrc: '/ui/workbench/model-detail/sketch-assets/gallery-3.png',
    isFavorited: true,
    isOwned: false,
    likesLabel: '39',
    title: 'River Stone Guardian',
    tone: 'steel',
    viewsLabel: '1.5k',
    visibility: 'public',
  },
  {
    ageLabel: '5 Days ago',
    createdAt: '2026-06-06T12:30:00.000Z',
    creatorId: 'nara-vale',
    favoritesLabel: '99',
    id: 'cask-carrying-keeper',
    imageSrc: '/ui/workbench/model-detail/sketch-assets/gallery-4.png',
    isFavorited: true,
    isOwned: false,
    likesLabel: '61',
    title: 'Cask Carrying Keeper',
    tone: 'green',
    viewsLabel: '942',
    visibility: 'public',
  },
  {
    ageLabel: '6 Days ago',
    createdAt: '2026-06-05T12:30:00.000Z',
    creatorId: 'nara-vale',
    favoritesLabel: '72',
    id: 'wayfarer-monk-set',
    imageSrc: '/ui-lab/workbench-assets/monk-large.webp',
    isFavorited: false,
    isOwned: false,
    likesLabel: '48',
    title: 'Wayfarer Monk Set',
    tone: 'amber',
    viewsLabel: '824',
    visibility: 'public',
  },
]
