/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-sqlite";
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  type AnySQLiteColumn,
  numeric,
} from "@payloadcms/db-sqlite/drizzle/sqlite-core";
import { sql, relations } from "@payloadcms/db-sqlite/drizzle";

export const users_sessions = sqliteTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    createdAt: text("created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    expiresAt: text("expires_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = sqliteTable(
  "users",
  {
    id: integer("id").primaryKey(),
    fullName: text("full_name"),
    role: text("role", { enum: ["admin", "operator", "customer"] })
      .notNull()
      .default("customer"),
    avatar: integer("avatar_id").references((): AnySQLiteColumn => media.id, {
      onDelete: "set null",
    }),
    phone: text("phone"),
    shopifyCustomerId: text("shopify_customer_id"),
    stripeCustomerId: text("stripe_customer_id"),
    creditsBalance: numeric("credits_balance", { mode: "number" }).default(0),
    lastActiveAt: text("last_active_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text("email").notNull(),
    resetPasswordToken: text("reset_password_token"),
    resetPasswordExpiration: text("reset_password_expiration").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text("salt"),
    hash: text("hash"),
    _verified: integer("_verified", { mode: "boolean" }),
    _verificationToken: text("_verificationtoken"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: text("lock_until").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
  (columns) => [
    index("users_avatar_idx").on(columns.avatar),
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = sqliteTable(
  "media",
  {
    id: integer("id").primaryKey(),
    alt: text("alt").notNull(),
    owner: integer("owner_id").references((): AnySQLiteColumn => users.id, {
      onDelete: "set null",
    }),
    purpose: text("purpose", {
      enum: ["input", "preview", "model", "document", "asset"],
    }).default("asset"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text("url"),
    thumbnailURL: text("thumbnail_u_r_l"),
    filename: text("filename"),
    mimeType: text("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_owner_idx").on(columns.owner),
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const generation_tasks = sqliteTable(
  "generation_tasks",
  {
    id: integer("id").primaryKey(),
    taskCode: text("task_code").notNull(),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    inputMode: text("input_mode", {
      enum: ["image", "text", "hybrid"],
    }).notNull(),
    prompt: text("prompt"),
    sourceImage: integer("source_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    provider: text("provider", { enum: ["meshy", "tripo", "custom"] }).default(
      "custom",
    ),
    providerTaskId: text("provider_task_id"),
    status: text("status", {
      enum: ["queued", "processing", "succeeded", "failed", "timeout"],
    })
      .notNull()
      .default("queued"),
    progress: numeric("progress", { mode: "number" }).default(0),
    parameterSnapshot: text("parameter_snapshot", { mode: "json" }),
    creditsReserved: numeric("credits_reserved", { mode: "number" }).default(0),
    creditsSpent: numeric("credits_spent", { mode: "number" }).default(0),
    resultModel: integer("result_model_id").references(
      (): AnySQLiteColumn => models.id,
      {
        onDelete: "set null",
      },
    ),
    printRequested: integer("print_requested", { mode: "boolean" }).default(
      false,
    ),
    startedAt: text("started_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    completedAt: text("completed_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    failureReason: text("failure_reason"),
    callbackPayload: text("callback_payload", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("generation_tasks_task_code_idx").on(columns.taskCode),
    index("generation_tasks_user_idx").on(columns.user),
    index("generation_tasks_source_image_idx").on(columns.sourceImage),
    index("generation_tasks_result_model_idx").on(columns.resultModel),
    index("generation_tasks_updated_at_idx").on(columns.updatedAt),
    index("generation_tasks_created_at_idx").on(columns.createdAt),
  ],
);

export const task_events = sqliteTable(
  "task_events",
  {
    id: integer("id").primaryKey(),
    task: integer("task_id")
      .notNull()
      .references(() => generation_tasks.id, {
        onDelete: "set null",
      }),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    eventType: text("event_type", {
      enum: [
        "queued",
        "submitted",
        "polling",
        "callback",
        "completed",
        "failed",
      ],
    }).notNull(),
    provider: text("provider"),
    message: text("message"),
    payload: text("payload", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("task_events_task_idx").on(columns.task),
    index("task_events_user_idx").on(columns.user),
    index("task_events_updated_at_idx").on(columns.updatedAt),
    index("task_events_created_at_idx").on(columns.createdAt),
  ],
);

export const models_formats = sqliteTable(
  "models_formats",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    format: text("format", {
      enum: ["glb", "fbx", "obj", "stl", "usdz"],
    }).notNull(),
    file: integer("file_id").references(() => media.id, {
      onDelete: "set null",
    }),
    downloadCredits: numeric("download_credits", { mode: "number" }).default(0),
    fileSizeMb: numeric("file_size_mb", { mode: "number" }),
  },
  (columns) => [
    index("models_formats_order_idx").on(columns._order),
    index("models_formats_parent_id_idx").on(columns._parentID),
    index("models_formats_file_idx").on(columns.file),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [models.id],
      name: "models_formats_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const models_tags = sqliteTable(
  "models_tags",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label"),
  },
  (columns) => [
    index("models_tags_order_idx").on(columns._order),
    index("models_tags_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [models.id],
      name: "models_tags_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const models = sqliteTable(
  "models",
  {
    id: integer("id").primaryKey(),
    title: text("title").notNull(),
    owner: integer("owner_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    sourceTask: integer("source_task_id").references(
      (): AnySQLiteColumn => generation_tasks.id,
      {
        onDelete: "set null",
      },
    ),
    status: text("status", { enum: ["draft", "ready", "archived"] }).default(
      "ready",
    ),
    visibility: text("visibility", {
      enum: ["private", "team", "public"],
    }).default("private"),
    previewImage: integer("preview_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    viewerUrl: text("viewer_url"),
    printReady: integer("print_ready", { mode: "boolean" }).default(false),
    dimensions_widthMm: numeric("dimensions_width_mm", { mode: "number" }),
    dimensions_heightMm: numeric("dimensions_height_mm", { mode: "number" }),
    dimensions_depthMm: numeric("dimensions_depth_mm", { mode: "number" }),
    description: text("description"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("models_owner_idx").on(columns.owner),
    index("models_source_task_idx").on(columns.sourceTask),
    index("models_preview_image_idx").on(columns.previewImage),
    index("models_updated_at_idx").on(columns.updatedAt),
    index("models_created_at_idx").on(columns.createdAt),
  ],
);

export const credits = sqliteTable(
  "credits",
  {
    id: integer("id").primaryKey(),
    accountLabel: text("account_label").notNull().default("主积分账户"),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    balance: numeric("balance", { mode: "number" }).notNull().default(0),
    reservedBalance: numeric("reserved_balance", { mode: "number" })
      .notNull()
      .default(0),
    lifetimePurchased: numeric("lifetime_purchased", { mode: "number" })
      .notNull()
      .default(0),
    lifetimeSpent: numeric("lifetime_spent", { mode: "number" })
      .notNull()
      .default(0),
    status: text("status", { enum: ["active", "suspended", "closed"] })
      .notNull()
      .default("active"),
    billingNotes: text("billing_notes"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("credits_user_idx").on(columns.user),
    index("credits_updated_at_idx").on(columns.updatedAt),
    index("credits_created_at_idx").on(columns.createdAt),
  ],
);

export const credit_transactions = sqliteTable(
  "credit_transactions",
  {
    id: integer("id").primaryKey(),
    referenceCode: text("reference_code").notNull(),
    idempotencyKey: text("idempotency_key"),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    creditAccount: integer("credit_account_id")
      .notNull()
      .references(() => credits.id, {
        onDelete: "set null",
      }),
    type: text("type", {
      enum: [
        "purchase",
        "task_hold",
        "task_spend",
        "download_spend",
        "refund",
        "manual_adjustment",
        "subscription_grant",
      ],
    }).notNull(),
    amount: numeric("amount", { mode: "number" }).notNull(),
    currency: text("currency").default("credits"),
    balanceAfter: numeric("balance_after", { mode: "number" }),
    sourceTask: integer("source_task_id").references(
      () => generation_tasks.id,
      {
        onDelete: "set null",
      },
    ),
    sourceOrder: integer("source_order_id").references(() => print_orders.id, {
      onDelete: "set null",
    }),
    notes: text("notes"),
    metadata: text("metadata", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("credit_transactions_reference_code_idx").on(
      columns.referenceCode,
    ),
    uniqueIndex("credit_transactions_idempotency_key_idx").on(
      columns.idempotencyKey,
    ),
    index("credit_transactions_user_idx").on(columns.user),
    index("credit_transactions_credit_account_idx").on(columns.creditAccount),
    index("credit_transactions_source_task_idx").on(columns.sourceTask),
    index("credit_transactions_source_order_idx").on(columns.sourceOrder),
    index("credit_transactions_updated_at_idx").on(columns.updatedAt),
    index("credit_transactions_created_at_idx").on(columns.createdAt),
  ],
);

export const credit_products = sqliteTable(
  "credit_products",
  {
    id: integer("id").primaryKey(),
    title: text("title").notNull(),
    slug: text("slug").notNull(),
    productType: text("product_type", {
      enum: ["credit-topup", "print-package"],
    }).default("credit-topup"),
    description: text("description"),
    credits: numeric("credits", { mode: "number" }).default(0),
    price: numeric("price", { mode: "number" }).notNull(),
    currency: text("currency").default("USD"),
    shopifyProductId: text("shopify_product_id"),
    shopifyVariantId: text("shopify_variant_id"),
    isFeatured: integer("is_featured", { mode: "boolean" }).default(false),
    isActive: integer("is_active", { mode: "boolean" }).default(true),
    sortOrder: numeric("sort_order", { mode: "number" }).default(0),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("credit_products_slug_idx").on(columns.slug),
    index("credit_products_updated_at_idx").on(columns.updatedAt),
    index("credit_products_created_at_idx").on(columns.createdAt),
  ],
);

export const billing_subscriptions = sqliteTable(
  "billing_subscriptions",
  {
    id: integer("id").primaryKey(),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    planKey: text("plan_key").notNull(),
    stripeCustomerId: text("stripe_customer_id").notNull(),
    stripeSubscriptionId: text("stripe_subscription_id").notNull(),
    stripePriceId: text("stripe_price_id").notNull(),
    status: text("status", {
      enum: [
        "incomplete",
        "active",
        "trialing",
        "past_due",
        "unpaid",
        "canceled",
        "incomplete_expired",
      ],
    })
      .notNull()
      .default("incomplete"),
    interval: text("interval").default("month"),
    monthlyCredits: numeric("monthly_credits", { mode: "number" }).default(0),
    currentPeriodStart: text("current_period_start").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    currentPeriodEnd: text("current_period_end").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    cancelAtPeriodEnd: integer("cancel_at_period_end", {
      mode: "boolean",
    }).default(false),
    lastGrantedPeriodKey: text("last_granted_period_key"),
    lastCheckoutSessionId: text("last_checkout_session_id"),
    metadata: text("metadata", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("billing_subscriptions_user_idx").on(columns.user),
    uniqueIndex("billing_subscriptions_stripe_subscription_id_idx").on(
      columns.stripeSubscriptionId,
    ),
    index("billing_subscriptions_updated_at_idx").on(columns.updatedAt),
    index("billing_subscriptions_created_at_idx").on(columns.createdAt),
  ],
);

export const addresses = sqliteTable(
  "addresses",
  {
    id: integer("id").primaryKey(),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    label: text("label"),
    recipientName: text("recipient_name").notNull(),
    phone: text("phone"),
    country: text("country").notNull().default("China"),
    province: text("province"),
    city: text("city").notNull(),
    district: text("district"),
    postalCode: text("postal_code"),
    addressLine1: text("address_line1").notNull(),
    addressLine2: text("address_line2"),
    isDefault: integer("is_default", { mode: "boolean" }).default(false),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("addresses_user_idx").on(columns.user),
    index("addresses_updated_at_idx").on(columns.updatedAt),
    index("addresses_created_at_idx").on(columns.createdAt),
  ],
);

export const print_orders = sqliteTable(
  "print_orders",
  {
    id: integer("id").primaryKey(),
    orderNumber: text("order_number").notNull(),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    model: integer("model_id")
      .notNull()
      .references(() => models.id, {
        onDelete: "set null",
      }),
    sourceTask: integer("source_task_id").references(
      () => generation_tasks.id,
      {
        onDelete: "set null",
      },
    ),
    status: text("status", {
      enum: [
        "pending-payment",
        "paid",
        "in-production",
        "shipped",
        "completed",
        "cancelled",
      ],
    })
      .notNull()
      .default("pending-payment"),
    paymentStatus: text("payment_status", {
      enum: ["pending", "paid", "failed", "refunded"],
    })
      .notNull()
      .default("pending"),
    shopifyOrderId: text("shopify_order_id"),
    amount: numeric("amount", { mode: "number" }).notNull().default(0),
    currency: text("currency").default("USD"),
    creditsUsed: numeric("credits_used", { mode: "number" }).default(0),
    sizeOption: text("size_option"),
    materialOption: text("material_option"),
    shippingName: text("shipping_name"),
    shippingPhone: text("shipping_phone"),
    shippingAddress: text("shipping_address"),
    trackingNumber: text("tracking_number"),
    shopifyCheckoutUrl: text("shopify_checkout_url"),
    internalNotes: text("internal_notes"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("print_orders_order_number_idx").on(columns.orderNumber),
    index("print_orders_user_idx").on(columns.user),
    index("print_orders_model_idx").on(columns.model),
    index("print_orders_source_task_idx").on(columns.sourceTask),
    index("print_orders_updated_at_idx").on(columns.updatedAt),
    index("print_orders_created_at_idx").on(columns.createdAt),
  ],
);

export const shopify_payments = sqliteTable(
  "shopify_payments",
  {
    id: integer("id").primaryKey(),
    checkoutReference: text("checkout_reference").notNull(),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    paymentType: text("payment_type", {
      enum: ["credit-topup", "print-order"],
    }).notNull(),
    status: text("status", {
      enum: ["pending", "paid", "failed", "refunded"],
    }).default("pending"),
    shopifyOrderId: text("shopify_order_id"),
    shopifyCheckoutId: text("shopify_checkout_id"),
    creditsGranted: numeric("credits_granted", { mode: "number" }).default(0),
    linkedOrder: integer("linked_order_id").references(() => print_orders.id, {
      onDelete: "set null",
    }),
    amount: numeric("amount", { mode: "number" }).notNull().default(0),
    currency: text("currency").default("USD"),
    rawWebhookPayload: text("raw_webhook_payload", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("shopify_payments_checkout_reference_idx").on(
      columns.checkoutReference,
    ),
    index("shopify_payments_user_idx").on(columns.user),
    index("shopify_payments_linked_order_idx").on(columns.linkedOrder),
    index("shopify_payments_updated_at_idx").on(columns.updatedAt),
    index("shopify_payments_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = sqliteTable(
  "payload_kv",
  {
    id: integer("id").primaryKey(),
    key: text("key").notNull(),
    data: text("data", { mode: "json" }).notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = sqliteTable(
  "payload_locked_documents",
  {
    id: integer("id").primaryKey(),
    globalSlug: text("global_slug"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = sqliteTable(
  "payload_locked_documents_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    "generation-tasksID": integer("generation_tasks_id"),
    "task-eventsID": integer("task_events_id"),
    modelsID: integer("models_id"),
    creditsID: integer("credits_id"),
    "credit-transactionsID": integer("credit_transactions_id"),
    "credit-productsID": integer("credit_products_id"),
    "billing-subscriptionsID": integer("billing_subscriptions_id"),
    addressesID: integer("addresses_id"),
    "print-ordersID": integer("print_orders_id"),
    "shopify-paymentsID": integer("shopify_payments_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_generation_tasks_id_idx").on(
      columns["generation-tasksID"],
    ),
    index("payload_locked_documents_rels_task_events_id_idx").on(
      columns["task-eventsID"],
    ),
    index("payload_locked_documents_rels_models_id_idx").on(columns.modelsID),
    index("payload_locked_documents_rels_credits_id_idx").on(columns.creditsID),
    index("payload_locked_documents_rels_credit_transactions_id_idx").on(
      columns["credit-transactionsID"],
    ),
    index("payload_locked_documents_rels_credit_products_id_idx").on(
      columns["credit-productsID"],
    ),
    index("payload_locked_documents_rels_billing_subscriptions_id_idx").on(
      columns["billing-subscriptionsID"],
    ),
    index("payload_locked_documents_rels_addresses_id_idx").on(
      columns.addressesID,
    ),
    index("payload_locked_documents_rels_print_orders_id_idx").on(
      columns["print-ordersID"],
    ),
    index("payload_locked_documents_rels_shopify_payments_id_idx").on(
      columns["shopify-paymentsID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["generation-tasksID"]],
      foreignColumns: [generation_tasks.id],
      name: "payload_locked_documents_rels_generation_tasks_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["task-eventsID"]],
      foreignColumns: [task_events.id],
      name: "payload_locked_documents_rels_task_events_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["modelsID"]],
      foreignColumns: [models.id],
      name: "payload_locked_documents_rels_models_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["creditsID"]],
      foreignColumns: [credits.id],
      name: "payload_locked_documents_rels_credits_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["credit-transactionsID"]],
      foreignColumns: [credit_transactions.id],
      name: "payload_locked_documents_rels_credit_transactions_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["credit-productsID"]],
      foreignColumns: [credit_products.id],
      name: "payload_locked_documents_rels_credit_products_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["billing-subscriptionsID"]],
      foreignColumns: [billing_subscriptions.id],
      name: "payload_locked_documents_rels_billing_subscriptions_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["addressesID"]],
      foreignColumns: [addresses.id],
      name: "payload_locked_documents_rels_addresses_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["print-ordersID"]],
      foreignColumns: [print_orders.id],
      name: "payload_locked_documents_rels_print_orders_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["shopify-paymentsID"]],
      foreignColumns: [shopify_payments.id],
      name: "payload_locked_documents_rels_shopify_payments_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = sqliteTable(
  "payload_preferences",
  {
    id: integer("id").primaryKey(),
    key: text("key"),
    value: text("value", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = sqliteTable(
  "payload_preferences_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = sqliteTable(
  "payload_migrations",
  {
    id: integer("id").primaryKey(),
    name: text("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const site_settings_header_nav = sqliteTable(
  "site_settings_header_nav",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label").notNull(),
    href: text("href").notNull(),
  },
  (columns) => [
    index("site_settings_header_nav_order_idx").on(columns._order),
    index("site_settings_header_nav_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_header_nav_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_subscription_plans_starter_features = sqliteTable(
  "site_settings_subscription_plans_starter_features",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label").notNull(),
  },
  (columns) => [
    index("site_settings_subscription_plans_starter_features_order_idx").on(
      columns._order,
    ),
    index("site_settings_subscription_plans_starter_features_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_subscription_plans_starter_features_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_subscription_plans_pro_features = sqliteTable(
  "site_settings_subscription_plans_pro_features",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label").notNull(),
  },
  (columns) => [
    index("site_settings_subscription_plans_pro_features_order_idx").on(
      columns._order,
    ),
    index("site_settings_subscription_plans_pro_features_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_subscription_plans_pro_features_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_subscription_plans_studio_features = sqliteTable(
  "site_settings_subscription_plans_studio_features",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label").notNull(),
  },
  (columns) => [
    index("site_settings_subscription_plans_studio_features_order_idx").on(
      columns._order,
    ),
    index("site_settings_subscription_plans_studio_features_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_subscription_plans_studio_features_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_credit_packages = sqliteTable(
  "site_settings_credit_packages",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    title: text("title").notNull(),
    shopifyVariantId: text("shopify_variant_id"),
    credits: numeric("credits", { mode: "number" }).notNull(),
    price: numeric("price", { mode: "number" }).notNull(),
    currency: text("currency").default("USD"),
  },
  (columns) => [
    index("site_settings_credit_packages_order_idx").on(columns._order),
    index("site_settings_credit_packages_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_credit_packages_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings = sqliteTable("site_settings", {
  id: integer("id").primaryKey(),
  siteName: text("site_name").notNull().default("MiniForge AI 3D"),
  siteDescription: text("site_description").default(
    "面向角色创作、模型资产管理和打印履约的一体化 AI 3D 产品平台。",
  ),
  supportEmail: text("support_email").default("support@example.com"),
  announcement: text("announcement").default(
    "内测版已支持营销站、生成工作台、订单与积分链路，欢迎继续补齐正式产品能力。",
  ),
  footer_aboutEyebrow: text("footer_about_eyebrow").default("关于产品"),
  footer_aboutTitle: text("footer_about_title").default(
    "面向角色创作、模型交付与打印履约的一体化平台",
  ),
  footer_aboutText: text("footer_about_text").default(
    "MiniForge 把角色生成、模型管理、下载交付与打印订单串成一条完整链路，让团队可以像运营正式产品一样运营 3D 资产。",
  ),
  footer_directionEyebrow: text("footer_direction_eyebrow").default("产品方向"),
  footer_directionTitle: text("footer_direction_title").default(
    "从 AI 生成工具升级为可运营的产品网站",
  ),
  footer_directionText: text("footer_direction_text").default(
    "当前版本已经具备账号、任务、模型、订单、积分与后台运营结构，下一步将继续补齐正式营销站、Studio 和平台 API。",
  ),
  paymentProviders_subscriptionProvider: text(
    "payment_providers_subscription_provider",
    { enum: ["stripe", "shopify"] },
  ).default("stripe"),
  paymentProviders_orderProvider: text("payment_providers_order_provider", {
    enum: ["stripe", "shopify"],
  }).default("stripe"),
  paymentProviders_providerNotice: text(
    "payment_providers_provider_notice",
  ).default(
    "当前版本正式启用 Stripe 处理订阅与订单支付；Shopify 相关数据结构继续保留，用于未来扩展商城/变体/结算链路。",
  ),
  subscriptionPlans_starter_name: text(
    "subscription_plans_starter_name",
  ).default("Starter"),
  subscriptionPlans_starter_shortLabel: text(
    "subscription_plans_starter_short_label",
  ).default("入门订阅"),
  subscriptionPlans_starter_monthlyPrice: numeric(
    "subscription_plans_starter_monthly_price",
    { mode: "number" },
  ).default(19),
  subscriptionPlans_starter_creditsPerMonth: numeric(
    "subscription_plans_starter_credits_per_month",
    { mode: "number" },
  ).default(240),
  subscriptionPlans_starter_description: text(
    "subscription_plans_starter_description",
  ).default("适合个人创作者持续生成角色、快速下载并维持轻量打印需求。"),
  subscriptionPlans_pro_name: text("subscription_plans_pro_name").default(
    "Pro",
  ),
  subscriptionPlans_pro_shortLabel: text(
    "subscription_plans_pro_short_label",
  ).default("专业订阅"),
  subscriptionPlans_pro_monthlyPrice: numeric(
    "subscription_plans_pro_monthly_price",
    { mode: "number" },
  ).default(49),
  subscriptionPlans_pro_creditsPerMonth: numeric(
    "subscription_plans_pro_credits_per_month",
    { mode: "number" },
  ).default(760),
  subscriptionPlans_pro_description: text(
    "subscription_plans_pro_description",
  ).default("适合高频创作、反复迭代与需要更稳定产能的小团队或工作室。"),
  subscriptionPlans_studio_name: text("subscription_plans_studio_name").default(
    "Studio",
  ),
  subscriptionPlans_studio_shortLabel: text(
    "subscription_plans_studio_short_label",
  ).default("工作室订阅"),
  subscriptionPlans_studio_monthlyPrice: numeric(
    "subscription_plans_studio_monthly_price",
    { mode: "number" },
  ).default(99),
  subscriptionPlans_studio_creditsPerMonth: numeric(
    "subscription_plans_studio_credits_per_month",
    { mode: "number" },
  ).default(1680),
  subscriptionPlans_studio_description: text(
    "subscription_plans_studio_description",
  ).default("适合把 AI 生成、资产沉淀与实体打样放进同一运营节奏的团队。"),
  generationPricing_imageCredits: numeric("generation_pricing_image_credits", {
    mode: "number",
  }).default(20),
  generationPricing_textCredits: numeric("generation_pricing_text_credits", {
    mode: "number",
  }).default(15),
  generationPricing_hybridCredits: numeric(
    "generation_pricing_hybrid_credits",
    { mode: "number" },
  ).default(25),
  generationPricing_downloadCredits: numeric(
    "generation_pricing_download_credits",
    { mode: "number" },
  ).default(5),
  emailSettings_sender_fromName: text(
    "email_settings_sender_from_name",
  ).default("MiniForge AI 3D"),
  emailSettings_sender_fromAddress: text(
    "email_settings_sender_from_address",
  ).default("no-reply@miniforge.local"),
  emailSettings_sender_replyTo: text("email_settings_sender_reply_to"),
  emailSettings_branding_productName: text(
    "email_settings_branding_product_name",
  ).default("MiniForge AI 3D"),
  emailSettings_branding_footerText: text(
    "email_settings_branding_footer_text",
  ).default("MiniForge AI 3D"),
  emailSettings_templates_welcome_subject: text(
    "email_settings_templates_welcome_subject",
  ).default("欢迎加入 MiniForge"),
  emailSettings_templates_welcome_intro: text(
    "email_settings_templates_welcome_intro",
  ).default(
    "你的账号已经创建成功，现在可以开始使用 MiniForge 的生成、模型、订阅与订单能力。",
  ),
  emailSettings_templates_welcome_ctaLabel: text(
    "email_settings_templates_welcome_cta_label",
  ).default("进入 Studio"),
  emailSettings_templates_verify_subject: text(
    "email_settings_templates_verify_subject",
  ).default("验证你的 MiniForge 邮箱"),
  emailSettings_templates_verify_intro: text(
    "email_settings_templates_verify_intro",
  ).default(
    "请点击下面的按钮完成邮箱验证，验证成功后即可登录并继续使用 MiniForge。",
  ),
  emailSettings_templates_verify_ctaLabel: text(
    "email_settings_templates_verify_cta_label",
  ).default("验证邮箱"),
  emailSettings_templates_forgotPassword_subject: text(
    "email_settings_templates_forgot_password_subject",
  ).default("MiniForge 密码重置"),
  emailSettings_templates_forgotPassword_intro: text(
    "email_settings_templates_forgot_password_intro",
  ).default("我们收到了你的密码重置请求。点击下面按钮即可设置新密码。"),
  emailSettings_templates_forgotPassword_ctaLabel: text(
    "email_settings_templates_forgot_password_cta_label",
  ).default("重置密码"),
  emailSettings_businessTemplates_subscriptionSuccess_subject: text(
    "email_settings_business_templates_subscription_success_subject",
  ).default("MiniForge 订阅开通成功"),
  emailSettings_businessTemplates_subscriptionSuccess_intro: text(
    "email_settings_business_templates_subscription_success_intro",
  ).default("你的订阅已经开通成功，积分已按当前账期发放到账户。"),
  emailSettings_businessTemplates_subscriptionSuccess_ctaLabel: text(
    "email_settings_business_templates_subscription_success_cta_label",
  ).default("查看积分与订阅"),
  emailSettings_businessTemplates_orderPaid_subject: text(
    "email_settings_business_templates_order_paid_subject",
  ).default("MiniForge 订单支付成功"),
  emailSettings_businessTemplates_orderPaid_intro: text(
    "email_settings_business_templates_order_paid_intro",
  ).default("你的打印订单已支付成功，订单已经进入后续处理流程。"),
  emailSettings_businessTemplates_orderPaid_ctaLabel: text(
    "email_settings_business_templates_order_paid_cta_label",
  ).default("查看订单详情"),
  updatedAt: text("updated_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  createdAt: text("created_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
});

export const homepage_content_featured_works = sqliteTable(
  "homepage_content_featured_works",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    category: text("category").notNull(),
    title: text("title").notNull(),
    summary: text("summary"),
    tone: text("tone", { enum: ["violet", "blue", "pink"] }).default("violet"),
  },
  (columns) => [
    index("homepage_content_featured_works_order_idx").on(columns._order),
    index("homepage_content_featured_works_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage_content.id],
      name: "homepage_content_featured_works_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const homepage_content_service_blocks = sqliteTable(
  "homepage_content_service_blocks",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    title: text("title").notNull(),
    text: text("text").notNull(),
  },
  (columns) => [
    index("homepage_content_service_blocks_order_idx").on(columns._order),
    index("homepage_content_service_blocks_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage_content.id],
      name: "homepage_content_service_blocks_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const homepage_content_use_cases = sqliteTable(
  "homepage_content_use_cases",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label").notNull(),
  },
  (columns) => [
    index("homepage_content_use_cases_order_idx").on(columns._order),
    index("homepage_content_use_cases_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage_content.id],
      name: "homepage_content_use_cases_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const homepage_content_process_steps = sqliteTable(
  "homepage_content_process_steps",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    step: text("step").notNull(),
    title: text("title").notNull(),
    text: text("text").notNull(),
  },
  (columns) => [
    index("homepage_content_process_steps_order_idx").on(columns._order),
    index("homepage_content_process_steps_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage_content.id],
      name: "homepage_content_process_steps_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const homepage_content_faq = sqliteTable(
  "homepage_content_faq",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    question: text("question").notNull(),
    answer: text("answer").notNull(),
  },
  (columns) => [
    index("homepage_content_faq_order_idx").on(columns._order),
    index("homepage_content_faq_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [homepage_content.id],
      name: "homepage_content_faq_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const homepage_content = sqliteTable("homepage_content", {
  id: integer("id").primaryKey(),
  hero_eyebrow: text("hero_eyebrow").default("MiniForge Studio"),
  hero_title: text("hero_title").default(
    "为角色创作、模型交付与打印履约而设计的 AI 3D 产品站。",
  ),
  hero_subtitle: text("hero_subtitle").default(
    "这不是一个孤立的功能入口，而是一套完整的产品体验：先展示作品、场景与能力，再自然进入生成、下载、打印与交付。",
  ),
  hero_primaryCTA_label: text("hero_primary_c_t_a_label").default(
    "进入 Studio",
  ),
  hero_primaryCTA_href: text("hero_primary_c_t_a_href").default("/generate"),
  hero_secondaryCTA_label: text("hero_secondary_c_t_a_label").default(
    "查看案例展示",
  ),
  hero_secondaryCTA_href: text("hero_secondary_c_t_a_href").default(
    "/showcase",
  ),
  introBand_eyebrow: text("intro_band_eyebrow").default("网站定位"),
  introBand_title: text("intro_band_title").default(
    "像一个正式产品网站一样，先讲清楚价值，再引导进入工作流。",
  ),
  introBand_text: text("intro_band_text").default(
    "首页应先展示作品、服务与场景，再承接行为入口，而不是把每一屏都做成操作说明。",
  ),
  serviceIntro_eyebrow: text("service_intro_eyebrow").default("我们在做什么"),
  serviceIntro_title: text("service_intro_title").default(
    "把角色创作、3D 结果与打印交付放进同一个产品里。",
  ),
  serviceIntro_text: text("service_intro_text").default(
    "对外表达上，这里更像一个数字制作品牌网站；真正的重点，是让访客知道自己可以在这里完成什么。",
  ),
  processSection_eyebrow: text("process_section_eyebrow").default("工作流程"),
  processSection_title: text("process_section_title").default(
    "从创意输入到模型交付，再到打印履约。",
  ),
  entrySection_eyebrow: text("entry_section_eyebrow").default("进入方式"),
  entrySection_title: text("entry_section_title").default(
    "先建立信任与认知，再引导用户进入操作流。",
  ),
  entrySection_text: text("entry_section_text").default(
    "如果访客已经理解产品价值，就应该能自然地进入生成、下载与打印流程，而不是一上来就被迫理解后台术语。",
  ),
  faqSection_eyebrow: text("faq_section_eyebrow").default("常见问题"),
  faqSection_title: text("faq_section_title").default(
    "把产品边界、交付方式和适用场景讲清楚。",
  ),
  updatedAt: text("updated_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  createdAt: text("created_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
});

export const ai_provider_settings_providers = sqliteTable(
  "ai_provider_settings_providers",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    provider: text("provider", {
      enum: ["custom", "meshy", "tripo"],
    }).notNull(),
    baseURL: text("base_u_r_l"),
    submitPath: text("submit_path"),
    statusPath: text("status_path"),
    apiKeyHint: text("api_key_hint"),
    enabled: integer("enabled", { mode: "boolean" }).default(true),
  },
  (columns) => [
    index("ai_provider_settings_providers_order_idx").on(columns._order),
    index("ai_provider_settings_providers_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [ai_provider_settings.id],
      name: "ai_provider_settings_providers_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const ai_provider_settings = sqliteTable("ai_provider_settings", {
  id: integer("id").primaryKey(),
  defaultProvider: text("default_provider", {
    enum: ["custom", "meshy", "tripo"],
  }).default("custom"),
  mockMode: integer("mock_mode", { mode: "boolean" }).default(true),
  credentialsNotice: text("credentials_notice").default(
    "Meshy API key, AI webhook secret, S3 access key ID, and S3 secret access key are no longer stored in Payload globals. Configure them in your hosting environment or secret manager instead.",
  ),
  polling_enabled: integer("polling_enabled", { mode: "boolean" }).default(
    true,
  ),
  polling_intervalSeconds: numeric("polling_interval_seconds", {
    mode: "number",
  }).default(20),
  polling_timeoutMinutes: numeric("polling_timeout_minutes", {
    mode: "number",
  }).default(8),
  creditRules_reserveOnSubmit: integer("credit_rules_reserve_on_submit", {
    mode: "boolean",
  }).default(true),
  creditRules_refundOnFailure: integer("credit_rules_refund_on_failure", {
    mode: "boolean",
  }).default(true),
  storage_enabled: integer("storage_enabled", { mode: "boolean" }).default(
    false,
  ),
  storage_bucket: text("storage_bucket"),
  storage_region: text("storage_region").default("us-east-1"),
  storage_prefix: text("storage_prefix").default("media"),
  storage_baseURL: text("storage_base_u_r_l"),
  storage_signedDownloads: integer("storage_signed_downloads", {
    mode: "boolean",
  }).default(true),
  storage_credentialsSource: text("storage_credentials_source").default(
    "environment",
  ),
  storage_lastValidatedAt: text("storage_last_validated_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  storage_lastRotatedAt: text("storage_last_rotated_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  meshy_credentialsSource: text("meshy_credentials_source").default(
    "environment",
  ),
  meshy_baseURL: text("meshy_base_u_r_l").default("https://api.meshy.ai"),
  meshy_textTo3DAiModel: text("meshy_text_to3_d_ai_model", {
    enum: ["latest", "meshy-6", "meshy-5"],
  }).default("latest"),
  meshy_imageTo3DAiModel: text("meshy_image_to3_d_ai_model", {
    enum: ["latest", "meshy-6", "meshy-5"],
  }).default("latest"),
  meshy_shouldTexture: integer("meshy_should_texture", {
    mode: "boolean",
  }).default(true),
  meshy_enablePBR: integer("meshy_enable_p_b_r", { mode: "boolean" }).default(
    false,
  ),
  meshy_moderation: integer("meshy_moderation", { mode: "boolean" }).default(
    false,
  ),
  meshy_imageEnhancement: integer("meshy_image_enhancement", {
    mode: "boolean",
  }).default(true),
  meshy_removeLighting: integer("meshy_remove_lighting", {
    mode: "boolean",
  }).default(true),
  meshy_lastValidatedAt: text("meshy_last_validated_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  meshy_lastRotatedAt: text("meshy_last_rotated_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  updatedAt: text("updated_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  createdAt: text("created_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
});

export const runtime_deployment_settings = sqliteTable(
  "runtime_deployment_settings",
  {
    id: integer("id").primaryKey(),
    databaseConnectionMode: text("database_connection_mode", {
      enum: ["aws-rds-fields", "database-url"],
    })
      .notNull()
      .default("aws-rds-fields"),
    databaseUrlTemplate: text("database_url_template"),
    awsRdsHost: text("aws_rds_host"),
    awsRdsPort: numeric("aws_rds_port", { mode: "number" }).default(5432),
    awsRdsDbName: text("aws_rds_db_name").default("payload_local_demo"),
    awsRdsUsername: text("aws_rds_username").default("payload_admin"),
    awsRdsSslMode: text("aws_rds_ssl_mode", {
      enum: ["require", "verify-full", "disable"],
    }).default("require"),
    awsRdsSslRejectUnauthorized: integer("aws_rds_ssl_reject_unauthorized", {
      mode: "boolean",
    }).default(false),
    databaseSecurityChecklist: text("database_security_checklist"),
    nextPublicAppUrl: text("next_public_app_url").default(
      "http://127.0.0.1:3000",
    ),
    payloadSecretRotationNote: text("payload_secret_rotation_note"),
    updatedAt: text("updated_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    createdAt: text("created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ one, many }) => ({
  avatar: one(media, {
    fields: [users.avatar],
    references: [media.id],
    relationName: "avatar",
  }),
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, ({ one }) => ({
  owner: one(users, {
    fields: [media.owner],
    references: [users.id],
    relationName: "owner",
  }),
}));
export const relations_generation_tasks = relations(
  generation_tasks,
  ({ one }) => ({
    user: one(users, {
      fields: [generation_tasks.user],
      references: [users.id],
      relationName: "user",
    }),
    sourceImage: one(media, {
      fields: [generation_tasks.sourceImage],
      references: [media.id],
      relationName: "sourceImage",
    }),
    resultModel: one(models, {
      fields: [generation_tasks.resultModel],
      references: [models.id],
      relationName: "resultModel",
    }),
  }),
);
export const relations_task_events = relations(task_events, ({ one }) => ({
  task: one(generation_tasks, {
    fields: [task_events.task],
    references: [generation_tasks.id],
    relationName: "task",
  }),
  user: one(users, {
    fields: [task_events.user],
    references: [users.id],
    relationName: "user",
  }),
}));
export const relations_models_formats = relations(
  models_formats,
  ({ one }) => ({
    _parentID: one(models, {
      fields: [models_formats._parentID],
      references: [models.id],
      relationName: "formats",
    }),
    file: one(media, {
      fields: [models_formats.file],
      references: [media.id],
      relationName: "file",
    }),
  }),
);
export const relations_models_tags = relations(models_tags, ({ one }) => ({
  _parentID: one(models, {
    fields: [models_tags._parentID],
    references: [models.id],
    relationName: "tags",
  }),
}));
export const relations_models = relations(models, ({ one, many }) => ({
  owner: one(users, {
    fields: [models.owner],
    references: [users.id],
    relationName: "owner",
  }),
  sourceTask: one(generation_tasks, {
    fields: [models.sourceTask],
    references: [generation_tasks.id],
    relationName: "sourceTask",
  }),
  previewImage: one(media, {
    fields: [models.previewImage],
    references: [media.id],
    relationName: "previewImage",
  }),
  formats: many(models_formats, {
    relationName: "formats",
  }),
  tags: many(models_tags, {
    relationName: "tags",
  }),
}));
export const relations_credits = relations(credits, ({ one }) => ({
  user: one(users, {
    fields: [credits.user],
    references: [users.id],
    relationName: "user",
  }),
}));
export const relations_credit_transactions = relations(
  credit_transactions,
  ({ one }) => ({
    user: one(users, {
      fields: [credit_transactions.user],
      references: [users.id],
      relationName: "user",
    }),
    creditAccount: one(credits, {
      fields: [credit_transactions.creditAccount],
      references: [credits.id],
      relationName: "creditAccount",
    }),
    sourceTask: one(generation_tasks, {
      fields: [credit_transactions.sourceTask],
      references: [generation_tasks.id],
      relationName: "sourceTask",
    }),
    sourceOrder: one(print_orders, {
      fields: [credit_transactions.sourceOrder],
      references: [print_orders.id],
      relationName: "sourceOrder",
    }),
  }),
);
export const relations_credit_products = relations(credit_products, () => ({}));
export const relations_billing_subscriptions = relations(
  billing_subscriptions,
  ({ one }) => ({
    user: one(users, {
      fields: [billing_subscriptions.user],
      references: [users.id],
      relationName: "user",
    }),
  }),
);
export const relations_addresses = relations(addresses, ({ one }) => ({
  user: one(users, {
    fields: [addresses.user],
    references: [users.id],
    relationName: "user",
  }),
}));
export const relations_print_orders = relations(print_orders, ({ one }) => ({
  user: one(users, {
    fields: [print_orders.user],
    references: [users.id],
    relationName: "user",
  }),
  model: one(models, {
    fields: [print_orders.model],
    references: [models.id],
    relationName: "model",
  }),
  sourceTask: one(generation_tasks, {
    fields: [print_orders.sourceTask],
    references: [generation_tasks.id],
    relationName: "sourceTask",
  }),
}));
export const relations_shopify_payments = relations(
  shopify_payments,
  ({ one }) => ({
    user: one(users, {
      fields: [shopify_payments.user],
      references: [users.id],
      relationName: "user",
    }),
    linkedOrder: one(print_orders, {
      fields: [shopify_payments.linkedOrder],
      references: [print_orders.id],
      relationName: "linkedOrder",
    }),
  }),
);
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    "generation-tasksID": one(generation_tasks, {
      fields: [payload_locked_documents_rels["generation-tasksID"]],
      references: [generation_tasks.id],
      relationName: "generation-tasks",
    }),
    "task-eventsID": one(task_events, {
      fields: [payload_locked_documents_rels["task-eventsID"]],
      references: [task_events.id],
      relationName: "task-events",
    }),
    modelsID: one(models, {
      fields: [payload_locked_documents_rels.modelsID],
      references: [models.id],
      relationName: "models",
    }),
    creditsID: one(credits, {
      fields: [payload_locked_documents_rels.creditsID],
      references: [credits.id],
      relationName: "credits",
    }),
    "credit-transactionsID": one(credit_transactions, {
      fields: [payload_locked_documents_rels["credit-transactionsID"]],
      references: [credit_transactions.id],
      relationName: "credit-transactions",
    }),
    "credit-productsID": one(credit_products, {
      fields: [payload_locked_documents_rels["credit-productsID"]],
      references: [credit_products.id],
      relationName: "credit-products",
    }),
    "billing-subscriptionsID": one(billing_subscriptions, {
      fields: [payload_locked_documents_rels["billing-subscriptionsID"]],
      references: [billing_subscriptions.id],
      relationName: "billing-subscriptions",
    }),
    addressesID: one(addresses, {
      fields: [payload_locked_documents_rels.addressesID],
      references: [addresses.id],
      relationName: "addresses",
    }),
    "print-ordersID": one(print_orders, {
      fields: [payload_locked_documents_rels["print-ordersID"]],
      references: [print_orders.id],
      relationName: "print-orders",
    }),
    "shopify-paymentsID": one(shopify_payments, {
      fields: [payload_locked_documents_rels["shopify-paymentsID"]],
      references: [shopify_payments.id],
      relationName: "shopify-payments",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_site_settings_header_nav = relations(
  site_settings_header_nav,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_header_nav._parentID],
      references: [site_settings.id],
      relationName: "headerNav",
    }),
  }),
);
export const relations_site_settings_subscription_plans_starter_features =
  relations(site_settings_subscription_plans_starter_features, ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_subscription_plans_starter_features._parentID],
      references: [site_settings.id],
      relationName: "subscriptionPlans_starter_features",
    }),
  }));
export const relations_site_settings_subscription_plans_pro_features =
  relations(site_settings_subscription_plans_pro_features, ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_subscription_plans_pro_features._parentID],
      references: [site_settings.id],
      relationName: "subscriptionPlans_pro_features",
    }),
  }));
export const relations_site_settings_subscription_plans_studio_features =
  relations(site_settings_subscription_plans_studio_features, ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_subscription_plans_studio_features._parentID],
      references: [site_settings.id],
      relationName: "subscriptionPlans_studio_features",
    }),
  }));
export const relations_site_settings_credit_packages = relations(
  site_settings_credit_packages,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_credit_packages._parentID],
      references: [site_settings.id],
      relationName: "creditPackages",
    }),
  }),
);
export const relations_site_settings = relations(site_settings, ({ many }) => ({
  headerNav: many(site_settings_header_nav, {
    relationName: "headerNav",
  }),
  subscriptionPlans_starter_features: many(
    site_settings_subscription_plans_starter_features,
    {
      relationName: "subscriptionPlans_starter_features",
    },
  ),
  subscriptionPlans_pro_features: many(
    site_settings_subscription_plans_pro_features,
    {
      relationName: "subscriptionPlans_pro_features",
    },
  ),
  subscriptionPlans_studio_features: many(
    site_settings_subscription_plans_studio_features,
    {
      relationName: "subscriptionPlans_studio_features",
    },
  ),
  creditPackages: many(site_settings_credit_packages, {
    relationName: "creditPackages",
  }),
}));
export const relations_homepage_content_featured_works = relations(
  homepage_content_featured_works,
  ({ one }) => ({
    _parentID: one(homepage_content, {
      fields: [homepage_content_featured_works._parentID],
      references: [homepage_content.id],
      relationName: "featuredWorks",
    }),
  }),
);
export const relations_homepage_content_service_blocks = relations(
  homepage_content_service_blocks,
  ({ one }) => ({
    _parentID: one(homepage_content, {
      fields: [homepage_content_service_blocks._parentID],
      references: [homepage_content.id],
      relationName: "serviceBlocks",
    }),
  }),
);
export const relations_homepage_content_use_cases = relations(
  homepage_content_use_cases,
  ({ one }) => ({
    _parentID: one(homepage_content, {
      fields: [homepage_content_use_cases._parentID],
      references: [homepage_content.id],
      relationName: "useCases",
    }),
  }),
);
export const relations_homepage_content_process_steps = relations(
  homepage_content_process_steps,
  ({ one }) => ({
    _parentID: one(homepage_content, {
      fields: [homepage_content_process_steps._parentID],
      references: [homepage_content.id],
      relationName: "processSteps",
    }),
  }),
);
export const relations_homepage_content_faq = relations(
  homepage_content_faq,
  ({ one }) => ({
    _parentID: one(homepage_content, {
      fields: [homepage_content_faq._parentID],
      references: [homepage_content.id],
      relationName: "faq",
    }),
  }),
);
export const relations_homepage_content = relations(
  homepage_content,
  ({ many }) => ({
    featuredWorks: many(homepage_content_featured_works, {
      relationName: "featuredWorks",
    }),
    serviceBlocks: many(homepage_content_service_blocks, {
      relationName: "serviceBlocks",
    }),
    useCases: many(homepage_content_use_cases, {
      relationName: "useCases",
    }),
    processSteps: many(homepage_content_process_steps, {
      relationName: "processSteps",
    }),
    faq: many(homepage_content_faq, {
      relationName: "faq",
    }),
  }),
);
export const relations_ai_provider_settings_providers = relations(
  ai_provider_settings_providers,
  ({ one }) => ({
    _parentID: one(ai_provider_settings, {
      fields: [ai_provider_settings_providers._parentID],
      references: [ai_provider_settings.id],
      relationName: "providers",
    }),
  }),
);
export const relations_ai_provider_settings = relations(
  ai_provider_settings,
  ({ many }) => ({
    providers: many(ai_provider_settings_providers, {
      relationName: "providers",
    }),
  }),
);
export const relations_runtime_deployment_settings = relations(
  runtime_deployment_settings,
  () => ({}),
);

type DatabaseSchema = {
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  generation_tasks: typeof generation_tasks;
  task_events: typeof task_events;
  models_formats: typeof models_formats;
  models_tags: typeof models_tags;
  models: typeof models;
  credits: typeof credits;
  credit_transactions: typeof credit_transactions;
  credit_products: typeof credit_products;
  billing_subscriptions: typeof billing_subscriptions;
  addresses: typeof addresses;
  print_orders: typeof print_orders;
  shopify_payments: typeof shopify_payments;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  site_settings_header_nav: typeof site_settings_header_nav;
  site_settings_subscription_plans_starter_features: typeof site_settings_subscription_plans_starter_features;
  site_settings_subscription_plans_pro_features: typeof site_settings_subscription_plans_pro_features;
  site_settings_subscription_plans_studio_features: typeof site_settings_subscription_plans_studio_features;
  site_settings_credit_packages: typeof site_settings_credit_packages;
  site_settings: typeof site_settings;
  homepage_content_featured_works: typeof homepage_content_featured_works;
  homepage_content_service_blocks: typeof homepage_content_service_blocks;
  homepage_content_use_cases: typeof homepage_content_use_cases;
  homepage_content_process_steps: typeof homepage_content_process_steps;
  homepage_content_faq: typeof homepage_content_faq;
  homepage_content: typeof homepage_content;
  ai_provider_settings_providers: typeof ai_provider_settings_providers;
  ai_provider_settings: typeof ai_provider_settings;
  runtime_deployment_settings: typeof runtime_deployment_settings;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_generation_tasks: typeof relations_generation_tasks;
  relations_task_events: typeof relations_task_events;
  relations_models_formats: typeof relations_models_formats;
  relations_models_tags: typeof relations_models_tags;
  relations_models: typeof relations_models;
  relations_credits: typeof relations_credits;
  relations_credit_transactions: typeof relations_credit_transactions;
  relations_credit_products: typeof relations_credit_products;
  relations_billing_subscriptions: typeof relations_billing_subscriptions;
  relations_addresses: typeof relations_addresses;
  relations_print_orders: typeof relations_print_orders;
  relations_shopify_payments: typeof relations_shopify_payments;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_site_settings_header_nav: typeof relations_site_settings_header_nav;
  relations_site_settings_subscription_plans_starter_features: typeof relations_site_settings_subscription_plans_starter_features;
  relations_site_settings_subscription_plans_pro_features: typeof relations_site_settings_subscription_plans_pro_features;
  relations_site_settings_subscription_plans_studio_features: typeof relations_site_settings_subscription_plans_studio_features;
  relations_site_settings_credit_packages: typeof relations_site_settings_credit_packages;
  relations_site_settings: typeof relations_site_settings;
  relations_homepage_content_featured_works: typeof relations_homepage_content_featured_works;
  relations_homepage_content_service_blocks: typeof relations_homepage_content_service_blocks;
  relations_homepage_content_use_cases: typeof relations_homepage_content_use_cases;
  relations_homepage_content_process_steps: typeof relations_homepage_content_process_steps;
  relations_homepage_content_faq: typeof relations_homepage_content_faq;
  relations_homepage_content: typeof relations_homepage_content;
  relations_ai_provider_settings_providers: typeof relations_ai_provider_settings_providers;
  relations_ai_provider_settings: typeof relations_ai_provider_settings;
  relations_runtime_deployment_settings: typeof relations_runtime_deployment_settings;
};

declare module "@payloadcms/db-sqlite" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
