/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'generation-tasks': GenerationTask;
    'task-events': TaskEvent;
    models: Model;
    credits: Credit;
    'credit-transactions': CreditTransaction;
    'credit-products': CreditProduct;
    'billing-subscriptions': BillingSubscription;
    addresses: Address;
    'print-orders': PrintOrder;
    'shopify-payments': ShopifyPayment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'generation-tasks': GenerationTasksSelect<false> | GenerationTasksSelect<true>;
    'task-events': TaskEventsSelect<false> | TaskEventsSelect<true>;
    models: ModelsSelect<false> | ModelsSelect<true>;
    credits: CreditsSelect<false> | CreditsSelect<true>;
    'credit-transactions': CreditTransactionsSelect<false> | CreditTransactionsSelect<true>;
    'credit-products': CreditProductsSelect<false> | CreditProductsSelect<true>;
    'billing-subscriptions': BillingSubscriptionsSelect<false> | BillingSubscriptionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    'print-orders': PrintOrdersSelect<false> | PrintOrdersSelect<true>;
    'shopify-payments': ShopifyPaymentsSelect<false> | ShopifyPaymentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'homepage-content': HomepageContent;
    'ai-provider-settings': AiProviderSetting;
    'runtime-deployment-settings': RuntimeDeploymentSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'homepage-content': HomepageContentSelect<false> | HomepageContentSelect<true>;
    'ai-provider-settings': AiProviderSettingsSelect<false> | AiProviderSettingsSelect<true>;
    'runtime-deployment-settings': RuntimeDeploymentSettingsSelect<false> | RuntimeDeploymentSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * 平台用户、角色、资料与账户总览。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName?: string | null;
  role: 'admin' | 'operator' | 'customer';
  avatar?: (number | null) | Media;
  phone?: string | null;
  shopifyCustomerId?: string | null;
  stripeCustomerId?: string | null;
  creditsBalance?: number | null;
  lastActiveAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * 图片、预览图和 3D 文件统一存放处。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  owner?: (number | null) | User;
  purpose?: ('input' | 'preview' | 'model' | 'document' | 'asset') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * 跟踪 AI 生成任务的排队、状态、回调和结果。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generation-tasks".
 */
export interface GenerationTask {
  id: number;
  taskCode: string;
  user: number | User;
  inputMode: 'image' | 'text' | 'hybrid';
  prompt?: string | null;
  sourceImage?: (number | null) | Media;
  provider?: ('meshy' | 'tripo' | 'custom') | null;
  providerTaskId?: string | null;
  status: 'queued' | 'processing' | 'succeeded' | 'failed' | 'timeout';
  progress?: number | null;
  parameterSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  creditsReserved?: number | null;
  creditsSpent?: number | null;
  resultModel?: (number | null) | Model;
  printRequested?: boolean | null;
  startedAt?: string | null;
  completedAt?: string | null;
  failureReason?: string | null;
  callbackPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 管理生成后的模型资产、文件格式和打印属性。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Model {
  id: number;
  title: string;
  owner: number | User;
  sourceTask?: (number | null) | GenerationTask;
  status?: ('draft' | 'ready' | 'archived') | null;
  visibility?: ('private' | 'team' | 'public') | null;
  previewImage?: (number | null) | Media;
  formats?:
    | {
        format: 'glb' | 'fbx' | 'obj' | 'stl' | 'usdz';
        file?: (number | null) | Media;
        downloadCredits?: number | null;
        fileSizeMb?: number | null;
        id?: string | null;
      }[]
    | null;
  viewerUrl?: string | null;
  printReady?: boolean | null;
  dimensions?: {
    widthMm?: number | null;
    heightMm?: number | null;
    depthMm?: number | null;
  };
  tags?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-events".
 */
export interface TaskEvent {
  id: number;
  task: number | GenerationTask;
  user: number | User;
  eventType: 'queued' | 'submitted' | 'polling' | 'callback' | 'completed' | 'failed';
  provider?: string | null;
  message?: string | null;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 管理用户积分余额、预扣与累计消费。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credits".
 */
export interface Credit {
  id: number;
  accountLabel: string;
  user: number | User;
  balance: number;
  reservedBalance: number;
  lifetimePurchased: number;
  lifetimeSpent: number;
  status: 'active' | 'suspended' | 'closed';
  billingNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 记录每一笔积分变动。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions".
 */
export interface CreditTransaction {
  id: number;
  referenceCode: string;
  idempotencyKey?: string | null;
  user: number | User;
  creditAccount: number | Credit;
  type:
    | 'purchase'
    | 'task_hold'
    | 'task_spend'
    | 'download_spend'
    | 'refund'
    | 'manual_adjustment'
    | 'subscription_grant';
  amount: number;
  currency?: string | null;
  balanceAfter?: number | null;
  sourceTask?: (number | null) | GenerationTask;
  sourceOrder?: (number | null) | PrintOrder;
  notes?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 管理模型打印订单、收货信息和生产状态。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "print-orders".
 */
export interface PrintOrder {
  id: number;
  orderNumber: string;
  user: number | User;
  model: number | Model;
  sourceTask?: (number | null) | GenerationTask;
  status: 'pending-payment' | 'paid' | 'in-production' | 'shipped' | 'completed' | 'cancelled';
  shopifyOrderId?: string | null;
  amount: number;
  currency?: string | null;
  creditsUsed?: number | null;
  sizeOption?: string | null;
  materialOption?: string | null;
  shippingName?: string | null;
  shippingPhone?: string | null;
  shippingAddress?: string | null;
  trackingNumber?: string | null;
  shopifyCheckoutUrl?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-products".
 */
export interface CreditProduct {
  id: number;
  title: string;
  slug: string;
  productType?: ('credit-topup' | 'print-package') | null;
  description?: string | null;
  credits?: number | null;
  price: number;
  currency?: string | null;
  shopifyProductId?: string | null;
  shopifyVariantId?: string | null;
  isFeatured?: boolean | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 记录 Stripe 订阅、当前周期和积分发放状态。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-subscriptions".
 */
export interface BillingSubscription {
  id: number;
  user: number | User;
  planKey: string;
  stripeCustomerId: string;
  stripeSubscriptionId: string;
  stripePriceId: string;
  status: 'incomplete' | 'active' | 'trialing' | 'past_due' | 'unpaid' | 'canceled' | 'incomplete_expired';
  interval?: string | null;
  monthlyCredits?: number | null;
  currentPeriodStart?: string | null;
  currentPeriodEnd?: string | null;
  cancelAtPeriodEnd?: boolean | null;
  lastGrantedPeriodKey?: string | null;
  lastCheckoutSessionId?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  user: number | User;
  label?: string | null;
  recipientName: string;
  phone?: string | null;
  country: string;
  province?: string | null;
  city: string;
  district?: string | null;
  postalCode?: string | null;
  addressLine1: string;
  addressLine2?: string | null;
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 记录从 Shopify 同步或模拟生成的支付记录。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopify-payments".
 */
export interface ShopifyPayment {
  id: number;
  checkoutReference: string;
  user: number | User;
  paymentType: 'credit-topup' | 'print-order';
  status?: ('pending' | 'paid' | 'failed' | 'refunded') | null;
  shopifyOrderId?: string | null;
  shopifyCheckoutId?: string | null;
  creditsGranted?: number | null;
  linkedOrder?: (number | null) | PrintOrder;
  amount: number;
  currency?: string | null;
  rawWebhookPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'generation-tasks';
        value: number | GenerationTask;
      } | null)
    | ({
        relationTo: 'task-events';
        value: number | TaskEvent;
      } | null)
    | ({
        relationTo: 'models';
        value: number | Model;
      } | null)
    | ({
        relationTo: 'credits';
        value: number | Credit;
      } | null)
    | ({
        relationTo: 'credit-transactions';
        value: number | CreditTransaction;
      } | null)
    | ({
        relationTo: 'credit-products';
        value: number | CreditProduct;
      } | null)
    | ({
        relationTo: 'billing-subscriptions';
        value: number | BillingSubscription;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'print-orders';
        value: number | PrintOrder;
      } | null)
    | ({
        relationTo: 'shopify-payments';
        value: number | ShopifyPayment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  avatar?: T;
  phone?: T;
  shopifyCustomerId?: T;
  stripeCustomerId?: T;
  creditsBalance?: T;
  lastActiveAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  owner?: T;
  purpose?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generation-tasks_select".
 */
export interface GenerationTasksSelect<T extends boolean = true> {
  taskCode?: T;
  user?: T;
  inputMode?: T;
  prompt?: T;
  sourceImage?: T;
  provider?: T;
  providerTaskId?: T;
  status?: T;
  progress?: T;
  parameterSnapshot?: T;
  creditsReserved?: T;
  creditsSpent?: T;
  resultModel?: T;
  printRequested?: T;
  startedAt?: T;
  completedAt?: T;
  failureReason?: T;
  callbackPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-events_select".
 */
export interface TaskEventsSelect<T extends boolean = true> {
  task?: T;
  user?: T;
  eventType?: T;
  provider?: T;
  message?: T;
  payload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models_select".
 */
export interface ModelsSelect<T extends boolean = true> {
  title?: T;
  owner?: T;
  sourceTask?: T;
  status?: T;
  visibility?: T;
  previewImage?: T;
  formats?:
    | T
    | {
        format?: T;
        file?: T;
        downloadCredits?: T;
        fileSizeMb?: T;
        id?: T;
      };
  viewerUrl?: T;
  printReady?: T;
  dimensions?:
    | T
    | {
        widthMm?: T;
        heightMm?: T;
        depthMm?: T;
      };
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credits_select".
 */
export interface CreditsSelect<T extends boolean = true> {
  accountLabel?: T;
  user?: T;
  balance?: T;
  reservedBalance?: T;
  lifetimePurchased?: T;
  lifetimeSpent?: T;
  status?: T;
  billingNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions_select".
 */
export interface CreditTransactionsSelect<T extends boolean = true> {
  referenceCode?: T;
  idempotencyKey?: T;
  user?: T;
  creditAccount?: T;
  type?: T;
  amount?: T;
  currency?: T;
  balanceAfter?: T;
  sourceTask?: T;
  sourceOrder?: T;
  notes?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-products_select".
 */
export interface CreditProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  productType?: T;
  description?: T;
  credits?: T;
  price?: T;
  currency?: T;
  shopifyProductId?: T;
  shopifyVariantId?: T;
  isFeatured?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-subscriptions_select".
 */
export interface BillingSubscriptionsSelect<T extends boolean = true> {
  user?: T;
  planKey?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  stripePriceId?: T;
  status?: T;
  interval?: T;
  monthlyCredits?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  cancelAtPeriodEnd?: T;
  lastGrantedPeriodKey?: T;
  lastCheckoutSessionId?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  recipientName?: T;
  phone?: T;
  country?: T;
  province?: T;
  city?: T;
  district?: T;
  postalCode?: T;
  addressLine1?: T;
  addressLine2?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "print-orders_select".
 */
export interface PrintOrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  user?: T;
  model?: T;
  sourceTask?: T;
  status?: T;
  shopifyOrderId?: T;
  amount?: T;
  currency?: T;
  creditsUsed?: T;
  sizeOption?: T;
  materialOption?: T;
  shippingName?: T;
  shippingPhone?: T;
  shippingAddress?: T;
  trackingNumber?: T;
  shopifyCheckoutUrl?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopify-payments_select".
 */
export interface ShopifyPaymentsSelect<T extends boolean = true> {
  checkoutReference?: T;
  user?: T;
  paymentType?: T;
  status?: T;
  shopifyOrderId?: T;
  shopifyCheckoutId?: T;
  creditsGranted?: T;
  linkedOrder?: T;
  amount?: T;
  currency?: T;
  rawWebhookPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * 统一管理站点品牌、导航、定价、积分套餐与邮件通知文案。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  supportEmail?: string | null;
  announcement?: string | null;
  headerNav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footer?: {
    aboutEyebrow?: string | null;
    aboutTitle?: string | null;
    aboutText?: string | null;
    directionEyebrow?: string | null;
    directionTitle?: string | null;
    directionText?: string | null;
  };
  paymentProviders?: {
    subscriptionProvider?: ('stripe' | 'shopify') | null;
    orderProvider?: ('stripe' | 'shopify') | null;
    providerNotice?: string | null;
  };
  subscriptionPlans?: {
    starter?: {
      name?: string | null;
      shortLabel?: string | null;
      monthlyPrice?: number | null;
      creditsPerMonth?: number | null;
      description?: string | null;
      features?:
        | {
            label: string;
            id?: string | null;
          }[]
        | null;
    };
    pro?: {
      name?: string | null;
      shortLabel?: string | null;
      monthlyPrice?: number | null;
      creditsPerMonth?: number | null;
      description?: string | null;
      features?:
        | {
            label: string;
            id?: string | null;
          }[]
        | null;
    };
    studio?: {
      name?: string | null;
      shortLabel?: string | null;
      monthlyPrice?: number | null;
      creditsPerMonth?: number | null;
      description?: string | null;
      features?:
        | {
            label: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  generationPricing?: {
    imageCredits?: number | null;
    textCredits?: number | null;
    hybridCredits?: number | null;
    downloadCredits?: number | null;
  };
  creditPackages?:
    | {
        title: string;
        shopifyVariantId?: string | null;
        credits: number;
        price: number;
        currency?: string | null;
        id?: string | null;
      }[]
    | null;
  emailSettings?: {
    sender?: {
      fromName?: string | null;
      fromAddress?: string | null;
      replyTo?: string | null;
    };
    branding?: {
      productName?: string | null;
      footerText?: string | null;
    };
    templates?: {
      welcome?: {
        subject?: string | null;
        intro?: string | null;
        ctaLabel?: string | null;
      };
      verify?: {
        subject?: string | null;
        intro?: string | null;
        ctaLabel?: string | null;
      };
      forgotPassword?: {
        subject?: string | null;
        intro?: string | null;
        ctaLabel?: string | null;
      };
    };
    businessTemplates?: {
      subscriptionSuccess?: {
        subject?: string | null;
        intro?: string | null;
        ctaLabel?: string | null;
      };
      orderPaid?: {
        subject?: string | null;
        intro?: string | null;
        ctaLabel?: string | null;
      };
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-content".
 */
export interface HomepageContent {
  id: number;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    primaryCTA?: {
      label?: string | null;
      href?: string | null;
    };
    secondaryCTA?: {
      label?: string | null;
      href?: string | null;
    };
  };
  introBand?: {
    eyebrow?: string | null;
    title?: string | null;
    text?: string | null;
  };
  featuredWorks?:
    | {
        category: string;
        title: string;
        summary?: string | null;
        tone?: ('violet' | 'blue' | 'pink') | null;
        id?: string | null;
      }[]
    | null;
  serviceIntro?: {
    eyebrow?: string | null;
    title?: string | null;
    text?: string | null;
  };
  serviceBlocks?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  useCases?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  processSection?: {
    eyebrow?: string | null;
    title?: string | null;
  };
  processSteps?:
    | {
        step: string;
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  entrySection?: {
    eyebrow?: string | null;
    title?: string | null;
    text?: string | null;
  };
  faqSection?: {
    eyebrow?: string | null;
    title?: string | null;
  };
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-provider-settings".
 */
export interface AiProviderSetting {
  id: number;
  defaultProvider?: ('custom' | 'meshy' | 'tripo') | null;
  mockMode?: boolean | null;
  webhookSecret?: string | null;
  polling?: {
    enabled?: boolean | null;
    intervalSeconds?: number | null;
    timeoutMinutes?: number | null;
  };
  creditRules?: {
    reserveOnSubmit?: boolean | null;
    refundOnFailure?: boolean | null;
  };
  storage?: {
    enabled?: boolean | null;
    bucket?: string | null;
    region?: string | null;
    accessKeyId?: string | null;
    secretAccessKey?: string | null;
    prefix?: string | null;
    baseURL?: string | null;
    signedDownloads?: boolean | null;
  };
  meshy?: {
    /**
     * 填入 Meshy API Key 后，前台生成任务会优先走 Meshy 真正接口。
     */
    apiKey?: string | null;
    baseURL?: string | null;
    textTo3DAiModel?: ('latest' | 'meshy-6' | 'meshy-5') | null;
    imageTo3DAiModel?: ('latest' | 'meshy-6' | 'meshy-5') | null;
    shouldTexture?: boolean | null;
    enablePBR?: boolean | null;
    moderation?: boolean | null;
    imageEnhancement?: boolean | null;
    removeLighting?: boolean | null;
  };
  providers?:
    | {
        provider: 'custom' | 'meshy' | 'tripo';
        baseURL?: string | null;
        submitPath?: string | null;
        statusPath?: string | null;
        apiKeyHint?: string | null;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage deployment-time database and app runtime variables. Secrets must still be stored in your hosting platform environment.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-deployment-settings".
 */
export interface RuntimeDeploymentSetting {
  id: number;
  databaseConnectionMode: 'aws-rds-fields' | 'database-url';
  /**
   * Paste the deployment DATABASE_URL template without the real password if you want.
   */
  databaseUrlTemplate?: string | null;
  awsRdsHost?: string | null;
  awsRdsPort?: number | null;
  awsRdsDbName?: string | null;
  awsRdsUsername?: string | null;
  awsRdsSslMode?: ('require' | 'verify-full' | 'disable') | null;
  awsRdsSslRejectUnauthorized?: boolean | null;
  /**
   * Optional operator notes such as current security group, public access status, or the production server IP to allow.
   */
  databaseSecurityChecklist?: string | null;
  nextPublicAppUrl?: string | null;
  /**
   * Optional note for operators about where the current PAYLOAD_SECRET lives and when it was rotated.
   */
  payloadSecretRotationNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  supportEmail?: T;
  announcement?: T;
  headerNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        aboutEyebrow?: T;
        aboutTitle?: T;
        aboutText?: T;
        directionEyebrow?: T;
        directionTitle?: T;
        directionText?: T;
      };
  paymentProviders?:
    | T
    | {
        subscriptionProvider?: T;
        orderProvider?: T;
        providerNotice?: T;
      };
  subscriptionPlans?:
    | T
    | {
        starter?:
          | T
          | {
              name?: T;
              shortLabel?: T;
              monthlyPrice?: T;
              creditsPerMonth?: T;
              description?: T;
              features?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
            };
        pro?:
          | T
          | {
              name?: T;
              shortLabel?: T;
              monthlyPrice?: T;
              creditsPerMonth?: T;
              description?: T;
              features?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
            };
        studio?:
          | T
          | {
              name?: T;
              shortLabel?: T;
              monthlyPrice?: T;
              creditsPerMonth?: T;
              description?: T;
              features?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
            };
      };
  generationPricing?:
    | T
    | {
        imageCredits?: T;
        textCredits?: T;
        hybridCredits?: T;
        downloadCredits?: T;
      };
  creditPackages?:
    | T
    | {
        title?: T;
        shopifyVariantId?: T;
        credits?: T;
        price?: T;
        currency?: T;
        id?: T;
      };
  emailSettings?:
    | T
    | {
        sender?:
          | T
          | {
              fromName?: T;
              fromAddress?: T;
              replyTo?: T;
            };
        branding?:
          | T
          | {
              productName?: T;
              footerText?: T;
            };
        templates?:
          | T
          | {
              welcome?:
                | T
                | {
                    subject?: T;
                    intro?: T;
                    ctaLabel?: T;
                  };
              verify?:
                | T
                | {
                    subject?: T;
                    intro?: T;
                    ctaLabel?: T;
                  };
              forgotPassword?:
                | T
                | {
                    subject?: T;
                    intro?: T;
                    ctaLabel?: T;
                  };
            };
        businessTemplates?:
          | T
          | {
              subscriptionSuccess?:
                | T
                | {
                    subject?: T;
                    intro?: T;
                    ctaLabel?: T;
                  };
              orderPaid?:
                | T
                | {
                    subject?: T;
                    intro?: T;
                    ctaLabel?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-content_select".
 */
export interface HomepageContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  introBand?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
      };
  featuredWorks?:
    | T
    | {
        category?: T;
        title?: T;
        summary?: T;
        tone?: T;
        id?: T;
      };
  serviceIntro?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
      };
  serviceBlocks?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  useCases?:
    | T
    | {
        label?: T;
        id?: T;
      };
  processSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  processSteps?:
    | T
    | {
        step?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  entrySection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
      };
  faqSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-provider-settings_select".
 */
export interface AiProviderSettingsSelect<T extends boolean = true> {
  defaultProvider?: T;
  mockMode?: T;
  webhookSecret?: T;
  polling?:
    | T
    | {
        enabled?: T;
        intervalSeconds?: T;
        timeoutMinutes?: T;
      };
  creditRules?:
    | T
    | {
        reserveOnSubmit?: T;
        refundOnFailure?: T;
      };
  storage?:
    | T
    | {
        enabled?: T;
        bucket?: T;
        region?: T;
        accessKeyId?: T;
        secretAccessKey?: T;
        prefix?: T;
        baseURL?: T;
        signedDownloads?: T;
      };
  meshy?:
    | T
    | {
        apiKey?: T;
        baseURL?: T;
        textTo3DAiModel?: T;
        imageTo3DAiModel?: T;
        shouldTexture?: T;
        enablePBR?: T;
        moderation?: T;
        imageEnhancement?: T;
        removeLighting?: T;
      };
  providers?:
    | T
    | {
        provider?: T;
        baseURL?: T;
        submitPath?: T;
        statusPath?: T;
        apiKeyHint?: T;
        enabled?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-deployment-settings_select".
 */
export interface RuntimeDeploymentSettingsSelect<T extends boolean = true> {
  databaseConnectionMode?: T;
  databaseUrlTemplate?: T;
  awsRdsHost?: T;
  awsRdsPort?: T;
  awsRdsDbName?: T;
  awsRdsUsername?: T;
  awsRdsSslMode?: T;
  awsRdsSslRejectUnauthorized?: T;
  databaseSecurityChecklist?: T;
  nextPublicAppUrl?: T;
  payloadSecretRotationNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}