/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'user-follows': UserFollow;
    'avatar-frame-styles': AvatarFrameStyle;
    media: Media;
    'generation-tasks': GenerationTask;
    'task-events': TaskEvent;
    models: Model;
    'model-comments': ModelComment;
    'model-likes': ModelLike;
    'model-favorites': ModelFavorite;
    'homepage-items': HomepageItem;
    posts: Post;
    announcements: Announcement;
    'model-bundles': ModelBundle;
    credits: Credit;
    'credit-transactions': CreditTransaction;
    'credit-products': CreditProduct;
    'engagement-views': EngagementView;
    'billing-subscriptions': BillingSubscription;
    addresses: Address;
    'print-orders': PrintOrder;
    'shopify-payments': ShopifyPayment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'user-follows': UserFollowsSelect<false> | UserFollowsSelect<true>;
    'avatar-frame-styles': AvatarFrameStylesSelect<false> | AvatarFrameStylesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'generation-tasks': GenerationTasksSelect<false> | GenerationTasksSelect<true>;
    'task-events': TaskEventsSelect<false> | TaskEventsSelect<true>;
    models: ModelsSelect<false> | ModelsSelect<true>;
    'model-comments': ModelCommentsSelect<false> | ModelCommentsSelect<true>;
    'model-likes': ModelLikesSelect<false> | ModelLikesSelect<true>;
    'model-favorites': ModelFavoritesSelect<false> | ModelFavoritesSelect<true>;
    'homepage-items': HomepageItemsSelect<false> | HomepageItemsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    'model-bundles': ModelBundlesSelect<false> | ModelBundlesSelect<true>;
    credits: CreditsSelect<false> | CreditsSelect<true>;
    'credit-transactions': CreditTransactionsSelect<false> | CreditTransactionsSelect<true>;
    'credit-products': CreditProductsSelect<false> | CreditProductsSelect<true>;
    'engagement-views': EngagementViewsSelect<false> | EngagementViewsSelect<true>;
    'billing-subscriptions': BillingSubscriptionsSelect<false> | BillingSubscriptionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    'print-orders': PrintOrdersSelect<false> | PrintOrdersSelect<true>;
    'shopify-payments': ShopifyPaymentsSelect<false> | ShopifyPaymentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'zh') | ('en' | 'zh')[];
  globals: {
    'site-settings': SiteSetting;
    'homepage-content': HomepageContent;
    'ai-provider-settings': AiProviderSetting;
    'storage-settings': StorageSetting;
    'security-settings': SecuritySetting;
    'runtime-deployment-settings': RuntimeDeploymentSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'homepage-content': HomepageContentSelect<false> | HomepageContentSelect<true>;
    'ai-provider-settings': AiProviderSettingsSelect<false> | AiProviderSettingsSelect<true>;
    'storage-settings': StorageSettingsSelect<false> | StorageSettingsSelect<true>;
    'security-settings': SecuritySettingsSelect<false> | SecuritySettingsSelect<true>;
    'runtime-deployment-settings': RuntimeDeploymentSettingsSelect<false> | RuntimeDeploymentSettingsSelect<true>;
  };
  locale: 'en' | 'zh';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage platform users, roles, profile data, and account status.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName?: string | null;
  displayName?: string | null;
  /**
   * Short public profile introduction for creator pages and model detail sidebars.
   */
  bio?: string | null;
  role: 'admin' | 'operator' | 'customer';
  avatar?: (number | null) | Media;
  /**
   * Creator profile banner shown on account and model detail surfaces. Field name is kept for compatibility.
   */
  profileBackground?: (number | null) | Media;
  /**
   * Horizontal focal point percentage for banner cropping.
   */
  profileBannerFocalX?: number | null;
  /**
   * Vertical focal point percentage for banner cropping.
   */
  profileBannerFocalY?: number | null;
  /**
   * Compatibility frame key. Rich frame metadata is managed in Avatar Frame Styles.
   */
  avatarFrame?: ('none' | 'ember' | 'kick' | 'emerald') | null;
  profileVisibility?: ('private' | 'public') | null;
  phone?: string | null;
  shopifyCustomerId?: string | null;
  stripeCustomerId?: string | null;
  creditsBalance?: number | null;
  profileViewCount?: number | null;
  followersCount?: number | null;
  followingCount?: number | null;
  lastActiveAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Store images, previews, and 3D files in one place.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  owner?: (number | null) | User;
  /**
   * Use preview for guest-readable model images. Use avatar and profile banner for user profile media. Keep model files as model and source assets as input.
   */
  purpose?: ('input' | 'avatar' | 'profile-banner' | 'preview' | 'model' | 'document' | 'asset') | null;
  /**
   * Enable this when administrators want guests to access this exact asset, including example files or public 3D files.
   */
  publicAccess?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-follows".
 */
export interface UserFollow {
  id: number;
  follower: number | User;
  followee: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage user-selectable avatar frame metadata, thumbnails, unlock rules, and ordering.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatar-frame-styles".
 */
export interface AvatarFrameStyle {
  id: number;
  /**
   * Stable frontend key. Keep it lowercase and do not reuse retired keys.
   */
  key: string;
  title: string;
  description?: string | null;
  thumbnail?: (number | null) | Media;
  frameImage?: (number | null) | Media;
  unlockRule?: ('free' | 'subscription' | 'event' | 'achievement') | null;
  isActive?: boolean | null;
  isUserSelectable?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Track AI generation queueing, status, callbacks, and outputs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generation-tasks".
 */
export interface GenerationTask {
  id: number;
  taskCode: string;
  user: number | User;
  inputMode: 'image' | 'text' | 'hybrid';
  prompt?: string | null;
  sourceImage?: (number | null) | Media;
  provider?: ('meshy' | 'tripo' | 'gemini-official' | 'gemini-third-party' | 'custom') | null;
  providerTaskId?: string | null;
  status: 'queued' | 'processing' | 'succeeded' | 'failed' | 'timeout';
  progress?: number | null;
  parameterSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  creditsReserved?: number | null;
  creditsSpent?: number | null;
  resultModel?: (number | null) | Model;
  printRequested?: boolean | null;
  startedAt?: string | null;
  completedAt?: string | null;
  failureReason?: string | null;
  callbackPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage generated model assets, file formats, and print properties.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Model {
  id: number;
  title: string;
  owner: number | User;
  sourceTask?: (number | null) | GenerationTask;
  status?: ('draft' | 'ready' | 'archived') | null;
  visibility?: ('private' | 'team' | 'public') | null;
  /**
   * Required for public models. The linked media should use purpose = preview.
   */
  previewImage?: (number | null) | Media;
  formats?:
    | {
        format: 'glb' | 'fbx' | 'obj' | 'stl' | 'usdz' | '3mf';
        file?: (number | null) | Media;
        downloadCredits?: number | null;
        fileSizeMb?: number | null;
        id?: string | null;
      }[]
    | null;
  viewerUrl?: string | null;
  printReady?: boolean | null;
  viewCount?: number | null;
  commentsCount?: number | null;
  likesCount?: number | null;
  favoritesCount?: number | null;
  dimensions?: {
    widthMm?: number | null;
    heightMm?: number | null;
    depthMm?: number | null;
  };
  tags?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-events".
 */
export interface TaskEvent {
  id: number;
  task: number | GenerationTask;
  user: number | User;
  eventType: 'queued' | 'submitted' | 'polling' | 'callback' | 'completed' | 'failed';
  provider?: string | null;
  message?: string | null;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-comments".
 */
export interface ModelComment {
  id: number;
  model: number | Model;
  author: number | User;
  status: 'visible' | 'hidden';
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-likes".
 */
export interface ModelLike {
  id: number;
  user: number | User;
  model: number | Model;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-favorites".
 */
export interface ModelFavorite {
  id: number;
  user: number | User;
  model: number | Model;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage homepage cards, placements, sorting, visibility, and publish timing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-items".
 */
export interface HomepageItem {
  id: number;
  title: string;
  /**
   * Stable unique key for homepage item lookup and future sync flows.
   */
  slug: string;
  placement:
    | 'hero-secondary'
    | 'featured-rail'
    | 'featured'
    | 'collection-shelf'
    | 'bundles'
    | 'announcements'
    | 'articles';
  contentType: 'custom' | 'model' | 'post' | 'announcement' | 'bundle';
  summary?: string | null;
  /**
   * Optional small label for homepage cards, such as Featured or New.
   */
  badgeLabel?: string | null;
  /**
   * Optional ribbon copy for image-led homepage cards.
   */
  ribbonLabel?: string | null;
  /**
   * Optional action label when a card renders a button or link label.
   */
  ctaLabel?: string | null;
  /**
   * Optional override for the cover image alt text on frontend cards.
   */
  altText?: string | null;
  railVariant?: ('standard' | 'wide') | null;
  /**
   * Example: Products x5. Used for collection shelf cards.
   */
  itemCountLabel?: string | null;
  coverImage?: (number | null) | Media;
  linkedModel?: (number | null) | Model;
  linkedPost?: (number | null) | Post;
  linkedAnnouncement?: (number | null) | Announcement;
  linkedBundle?: (number | null) | ModelBundle;
  /**
   * Used when content type is custom. Supports internal or external destinations.
   */
  customHref?: string | null;
  createdBy?: (number | null) | User;
  publishAt?: string | null;
  isPinned?: boolean | null;
  isVisible?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage articles, event posts, and detail-page content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * 用于内容详情页的唯一标识，建议保持稳定且仅使用 URL 友好字符。
   */
  slug: string;
  category: 'article' | 'event' | 'announcement';
  coverImage?: (number | null) | Media;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * 支持 YouTube 等第三方视频链接，用于内容详情页嵌入。
   */
  videoUrl?: string | null;
  createdBy?: (number | null) | User;
  publishedAt?: string | null;
  isPinned?: boolean | null;
  isVisible?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage homepage announcements, system notices, and short-form prompts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  createdBy?: (number | null) | User;
  publishAt?: string | null;
  isPinned?: boolean | null;
  isVisible?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Combine multiple models into bundles, curated sets, and featured series.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-bundles".
 */
export interface ModelBundle {
  id: number;
  title: string;
  slug: string;
  coverImage?: (number | null) | Media;
  summary?: string | null;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 从现有用户生成的模型中选择一个或多个模型组成专题包。
   */
  models: (number | Model)[];
  createdBy?: (number | null) | User;
  publishAt?: string | null;
  isVisible?: boolean | null;
  isFeatured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage user credit balances, reserved credits, and lifetime usage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credits".
 */
export interface Credit {
  id: number;
  accountLabel: string;
  user: number | User;
  balance: number;
  reservedBalance: number;
  lifetimePurchased: number;
  lifetimeSpent: number;
  status: 'active' | 'suspended' | 'closed';
  billingNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Record every credit balance change.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions".
 */
export interface CreditTransaction {
  id: number;
  referenceCode: string;
  idempotencyKey?: string | null;
  user: number | User;
  creditAccount: number | Credit;
  type:
    | 'purchase'
    | 'task_hold'
    | 'task_spend'
    | 'download_spend'
    | 'refund'
    | 'manual_adjustment'
    | 'subscription_grant';
  amount: number;
  currency?: string | null;
  balanceAfter?: number | null;
  sourceTask?: (number | null) | GenerationTask;
  sourceOrder?: (number | null) | PrintOrder;
  notes?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage model print orders, shipping information, and production status.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "print-orders".
 */
export interface PrintOrder {
  id: number;
  orderNumber: string;
  user: number | User;
  model: number | Model;
  sourceTask?: (number | null) | GenerationTask;
  status: 'pending-payment' | 'paid' | 'in-production' | 'shipped' | 'completed' | 'cancelled';
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded';
  /**
   * 历史字段名保留为 shopifyOrderId，当前用于存放实际支付通道返回的订单/会话参考号。
   */
  shopifyOrderId?: string | null;
  amount: number;
  currency?: string | null;
  creditsUsed?: number | null;
  sizeOption?: string | null;
  materialOption?: string | null;
  shippingName?: string | null;
  shippingPhone?: string | null;
  shippingAddress?: string | null;
  trackingNumber?: string | null;
  /**
   * 历史字段名保留为 shopifyCheckoutUrl，当前 Stripe Checkout URL 也写入此处。
   */
  shopifyCheckoutUrl?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-products".
 */
export interface CreditProduct {
  id: number;
  title: string;
  slug: string;
  productType?: ('credit-topup' | 'print-package') | null;
  description?: string | null;
  credits?: number | null;
  price: number;
  currency?: string | null;
  shopifyProductId?: string | null;
  shopifyVariantId?: string | null;
  isFeatured?: boolean | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagement-views".
 */
export interface EngagementView {
  id: number;
  targetType: 'creator-profile' | 'model';
  targetUser?: (number | null) | User;
  targetModel?: (number | null) | Model;
  viewer?: (number | null) | User;
  viewerKeyHash: string;
  lastViewedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Track Stripe subscriptions, billing periods, and credit grant status.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-subscriptions".
 */
export interface BillingSubscription {
  id: number;
  user: number | User;
  planKey: string;
  stripeCustomerId: string;
  stripeSubscriptionId: string;
  stripePriceId: string;
  status: 'incomplete' | 'active' | 'trialing' | 'past_due' | 'unpaid' | 'canceled' | 'incomplete_expired';
  interval?: string | null;
  monthlyCredits?: number | null;
  currentPeriodStart?: string | null;
  currentPeriodEnd?: string | null;
  cancelAtPeriodEnd?: boolean | null;
  lastGrantedPeriodKey?: string | null;
  lastCheckoutSessionId?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  user: number | User;
  label?: string | null;
  recipientName: string;
  phone?: string | null;
  country: string;
  province?: string | null;
  city: string;
  district?: string | null;
  postalCode?: string | null;
  addressLine1: string;
  addressLine2?: string | null;
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Centralize platform payment records. Stripe is the active payment rail while Shopify compatibility fields remain for future migration.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopify-payments".
 */
export interface ShopifyPayment {
  id: number;
  checkoutReference: string;
  user: number | User;
  paymentType: 'credit-topup' | 'print-order';
  status?: ('pending' | 'paid' | 'failed' | 'refunded') | null;
  /**
   * 历史字段名保留为 shopifyOrderId，当前可用于存储 Stripe/Shopify 订单参考号。
   */
  shopifyOrderId?: string | null;
  /**
   * 历史字段名保留为 shopifyCheckoutId，当前 Stripe Checkout Session ID 也写入此处。
   */
  shopifyCheckoutId?: string | null;
  creditsGranted?: number | null;
  linkedOrder?: (number | null) | PrintOrder;
  amount: number;
  currency?: string | null;
  rawWebhookPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'user-follows';
        value: number | UserFollow;
      } | null)
    | ({
        relationTo: 'avatar-frame-styles';
        value: number | AvatarFrameStyle;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'generation-tasks';
        value: number | GenerationTask;
      } | null)
    | ({
        relationTo: 'task-events';
        value: number | TaskEvent;
      } | null)
    | ({
        relationTo: 'models';
        value: number | Model;
      } | null)
    | ({
        relationTo: 'model-comments';
        value: number | ModelComment;
      } | null)
    | ({
        relationTo: 'model-likes';
        value: number | ModelLike;
      } | null)
    | ({
        relationTo: 'model-favorites';
        value: number | ModelFavorite;
      } | null)
    | ({
        relationTo: 'homepage-items';
        value: number | HomepageItem;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'model-bundles';
        value: number | ModelBundle;
      } | null)
    | ({
        relationTo: 'credits';
        value: number | Credit;
      } | null)
    | ({
        relationTo: 'credit-transactions';
        value: number | CreditTransaction;
      } | null)
    | ({
        relationTo: 'credit-products';
        value: number | CreditProduct;
      } | null)
    | ({
        relationTo: 'engagement-views';
        value: number | EngagementView;
      } | null)
    | ({
        relationTo: 'billing-subscriptions';
        value: number | BillingSubscription;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'print-orders';
        value: number | PrintOrder;
      } | null)
    | ({
        relationTo: 'shopify-payments';
        value: number | ShopifyPayment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  displayName?: T;
  bio?: T;
  role?: T;
  avatar?: T;
  profileBackground?: T;
  profileBannerFocalX?: T;
  profileBannerFocalY?: T;
  avatarFrame?: T;
  profileVisibility?: T;
  phone?: T;
  shopifyCustomerId?: T;
  stripeCustomerId?: T;
  creditsBalance?: T;
  profileViewCount?: T;
  followersCount?: T;
  followingCount?: T;
  lastActiveAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-follows_select".
 */
export interface UserFollowsSelect<T extends boolean = true> {
  follower?: T;
  followee?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatar-frame-styles_select".
 */
export interface AvatarFrameStylesSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  description?: T;
  thumbnail?: T;
  frameImage?: T;
  unlockRule?: T;
  isActive?: T;
  isUserSelectable?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  owner?: T;
  purpose?: T;
  publicAccess?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generation-tasks_select".
 */
export interface GenerationTasksSelect<T extends boolean = true> {
  taskCode?: T;
  user?: T;
  inputMode?: T;
  prompt?: T;
  sourceImage?: T;
  provider?: T;
  providerTaskId?: T;
  status?: T;
  progress?: T;
  parameterSnapshot?: T;
  creditsReserved?: T;
  creditsSpent?: T;
  resultModel?: T;
  printRequested?: T;
  startedAt?: T;
  completedAt?: T;
  failureReason?: T;
  callbackPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-events_select".
 */
export interface TaskEventsSelect<T extends boolean = true> {
  task?: T;
  user?: T;
  eventType?: T;
  provider?: T;
  message?: T;
  payload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models_select".
 */
export interface ModelsSelect<T extends boolean = true> {
  title?: T;
  owner?: T;
  sourceTask?: T;
  status?: T;
  visibility?: T;
  previewImage?: T;
  formats?:
    | T
    | {
        format?: T;
        file?: T;
        downloadCredits?: T;
        fileSizeMb?: T;
        id?: T;
      };
  viewerUrl?: T;
  printReady?: T;
  viewCount?: T;
  commentsCount?: T;
  likesCount?: T;
  favoritesCount?: T;
  dimensions?:
    | T
    | {
        widthMm?: T;
        heightMm?: T;
        depthMm?: T;
      };
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-comments_select".
 */
export interface ModelCommentsSelect<T extends boolean = true> {
  model?: T;
  author?: T;
  status?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-likes_select".
 */
export interface ModelLikesSelect<T extends boolean = true> {
  user?: T;
  model?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-favorites_select".
 */
export interface ModelFavoritesSelect<T extends boolean = true> {
  user?: T;
  model?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-items_select".
 */
export interface HomepageItemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  placement?: T;
  contentType?: T;
  summary?: T;
  badgeLabel?: T;
  ribbonLabel?: T;
  ctaLabel?: T;
  altText?: T;
  railVariant?: T;
  itemCountLabel?: T;
  coverImage?: T;
  linkedModel?: T;
  linkedPost?: T;
  linkedAnnouncement?: T;
  linkedBundle?: T;
  customHref?: T;
  createdBy?: T;
  publishAt?: T;
  isPinned?: T;
  isVisible?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  coverImage?: T;
  excerpt?: T;
  content?: T;
  videoUrl?: T;
  createdBy?: T;
  publishedAt?: T;
  isPinned?: T;
  isVisible?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  content?: T;
  createdBy?: T;
  publishAt?: T;
  isPinned?: T;
  isVisible?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-bundles_select".
 */
export interface ModelBundlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  coverImage?: T;
  summary?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  models?: T;
  createdBy?: T;
  publishAt?: T;
  isVisible?: T;
  isFeatured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credits_select".
 */
export interface CreditsSelect<T extends boolean = true> {
  accountLabel?: T;
  user?: T;
  balance?: T;
  reservedBalance?: T;
  lifetimePurchased?: T;
  lifetimeSpent?: T;
  status?: T;
  billingNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions_select".
 */
export interface CreditTransactionsSelect<T extends boolean = true> {
  referenceCode?: T;
  idempotencyKey?: T;
  user?: T;
  creditAccount?: T;
  type?: T;
  amount?: T;
  currency?: T;
  balanceAfter?: T;
  sourceTask?: T;
  sourceOrder?: T;
  notes?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-products_select".
 */
export interface CreditProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  productType?: T;
  description?: T;
  credits?: T;
  price?: T;
  currency?: T;
  shopifyProductId?: T;
  shopifyVariantId?: T;
  isFeatured?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagement-views_select".
 */
export interface EngagementViewsSelect<T extends boolean = true> {
  targetType?: T;
  targetUser?: T;
  targetModel?: T;
  viewer?: T;
  viewerKeyHash?: T;
  lastViewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-subscriptions_select".
 */
export interface BillingSubscriptionsSelect<T extends boolean = true> {
  user?: T;
  planKey?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  stripePriceId?: T;
  status?: T;
  interval?: T;
  monthlyCredits?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  cancelAtPeriodEnd?: T;
  lastGrantedPeriodKey?: T;
  lastCheckoutSessionId?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  recipientName?: T;
  phone?: T;
  country?: T;
  province?: T;
  city?: T;
  district?: T;
  postalCode?: T;
  addressLine1?: T;
  addressLine2?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "print-orders_select".
 */
export interface PrintOrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  user?: T;
  model?: T;
  sourceTask?: T;
  status?: T;
  paymentStatus?: T;
  shopifyOrderId?: T;
  amount?: T;
  currency?: T;
  creditsUsed?: T;
  sizeOption?: T;
  materialOption?: T;
  shippingName?: T;
  shippingPhone?: T;
  shippingAddress?: T;
  trackingNumber?: T;
  shopifyCheckoutUrl?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopify-payments_select".
 */
export interface ShopifyPaymentsSelect<T extends boolean = true> {
  checkoutReference?: T;
  user?: T;
  paymentType?: T;
  status?: T;
  shopifyOrderId?: T;
  shopifyCheckoutId?: T;
  creditsGranted?: T;
  linkedOrder?: T;
  amount?: T;
  currency?: T;
  rawWebhookPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage site brand settings, navigation, pricing, credit plans, and notification copy from one place.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  supportEmail?: string | null;
  announcement?: string | null;
  headerNav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footer?: {
    aboutEyebrow?: string | null;
    aboutTitle?: string | null;
    aboutText?: string | null;
    directionEyebrow?: string | null;
    directionTitle?: string | null;
    directionText?: string | null;
  };
  paymentProviders?: {
    subscriptionProvider?: ('stripe' | 'shopify') | null;
    orderProvider?: ('stripe' | 'shopify') | null;
    providerNotice?: string | null;
  };
  subscriptionPlans?: {
    starter?: {
      name?: string | null;
      shortLabel?: string | null;
      monthlyPrice?: number | null;
      creditsPerMonth?: number | null;
      description?: string | null;
      features?:
        | {
            label: string;
            id?: string | null;
          }[]
        | null;
    };
    pro?: {
      name?: string | null;
      shortLabel?: string | null;
      monthlyPrice?: number | null;
      creditsPerMonth?: number | null;
      description?: string | null;
      features?:
        | {
            label: string;
            id?: string | null;
          }[]
        | null;
    };
    studio?: {
      name?: string | null;
      shortLabel?: string | null;
      monthlyPrice?: number | null;
      creditsPerMonth?: number | null;
      description?: string | null;
      features?:
        | {
            label: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  generationPricing?: {
    imageCredits?: number | null;
    textCredits?: number | null;
    hybridCredits?: number | null;
    downloadCredits?: number | null;
  };
  modelAccessPolicy?: {
    /**
     * Default off. Keep imported public model previews free until an operator enables charging.
     */
    chargePreviewCredits?: boolean | null;
    previewCredits?: number | null;
    /**
     * Default off. Download charging must remain server-side and refundable on delivery failure.
     */
    chargeDownloadCredits?: boolean | null;
    downloadCredits?: number | null;
  };
  creditPackages?:
    | {
        title: string;
        shopifyVariantId?: string | null;
        credits: number;
        price: number;
        currency?: string | null;
        id?: string | null;
      }[]
    | null;
  emailSettings?: {
    sender?: {
      fromName?: string | null;
      fromAddress?: string | null;
      replyTo?: string | null;
    };
    branding?: {
      productName?: string | null;
      footerText?: string | null;
    };
    templates?: {
      welcome?: {
        subject?: string | null;
        intro?: string | null;
        ctaLabel?: string | null;
      };
      verify?: {
        subject?: string | null;
        intro?: string | null;
        ctaLabel?: string | null;
      };
      forgotPassword?: {
        subject?: string | null;
        intro?: string | null;
        ctaLabel?: string | null;
      };
    };
    businessTemplates?: {
      subscriptionSuccess?: {
        subject?: string | null;
        intro?: string | null;
        ctaLabel?: string | null;
      };
      orderPaid?: {
        subject?: string | null;
        intro?: string | null;
        ctaLabel?: string | null;
      };
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-content".
 */
export interface HomepageContent {
  id: number;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    primaryCTA?: {
      label?: string | null;
      href?: string | null;
    };
    secondaryCTA?: {
      label?: string | null;
      href?: string | null;
    };
  };
  introBand?: {
    eyebrow?: string | null;
    title?: string | null;
    text?: string | null;
  };
  featuredRail?: {
    eyebrow?: string | null;
    title?: string | null;
    searchLabel?: string | null;
    moreLabel?: string | null;
  };
  featuredWorks?:
    | {
        category: string;
        title: string;
        summary?: string | null;
        tone?: ('violet' | 'blue' | 'pink') | null;
        id?: string | null;
      }[]
    | null;
  serviceIntro?: {
    eyebrow?: string | null;
    title?: string | null;
    text?: string | null;
  };
  collectionShelf?: {
    title?: string | null;
    hotLabel?: string | null;
    newLabel?: string | null;
    moreLabel?: string | null;
    allLabel?: string | null;
  };
  serviceBlocks?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  useCases?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  processSection?: {
    eyebrow?: string | null;
    title?: string | null;
  };
  processSteps?:
    | {
        step: string;
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  entrySection?: {
    eyebrow?: string | null;
    title?: string | null;
    text?: string | null;
  };
  faqSection?: {
    eyebrow?: string | null;
    title?: string | null;
  };
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage non-sensitive AI provider metadata here. Storage settings now live in the dedicated Storage Settings global, while real secrets must stay in hosting environment variables.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-provider-settings".
 */
export interface AiProviderSetting {
  id: number;
  defaultProvider?: ('custom' | 'meshy' | 'tripo') | null;
  mockMode?: boolean | null;
  credentialsNotice?: string | null;
  polling?: {
    enabled?: boolean | null;
    intervalSeconds?: number | null;
    timeoutMinutes?: number | null;
  };
  creditRules?: {
    reserveOnSubmit?: boolean | null;
    refundOnFailure?: boolean | null;
  };
  meshy?: {
    credentialsSource?: string | null;
    baseURL?: string | null;
    /**
     * Environment variables are safer. Use Payload admin override only when operators need to switch Meshy keys from the backend UI.
     */
    apiKeyMode?: ('environment' | 'payload') | null;
    /**
     * Stored in the Payload database and never sent to the frontend. Prefer MESHY_API_KEY in production when possible.
     */
    apiKey?: string | null;
    textTo3DAiModel?: ('latest' | 'meshy-6' | 'meshy-5') | null;
    imageTo3DAiModel?: ('latest' | 'meshy-6' | 'meshy-5') | null;
    shouldTexture?: boolean | null;
    enablePBR?: boolean | null;
    hdTexture?: boolean | null;
    multiImageEnabled?: boolean | null;
    pricing?: {
      textTo3DCredits?: number | null;
      imageTo3DCredits?: number | null;
      multiImageTo3DCredits?: number | null;
    };
    modelType?: ('standard' | 'lowpoly') | null;
    topology?: ('triangle' | 'quad') | null;
    targetPolycount?: number | null;
    targetFormats?: ('glb' | 'obj' | 'fbx' | 'stl' | 'usdz' | '3mf')[] | null;
    moderation?: boolean | null;
    imageEnhancement?: boolean | null;
    removeLighting?: boolean | null;
    lastValidatedAt?: string | null;
    lastRotatedAt?: string | null;
  };
  providers?:
    | {
        provider: 'custom' | 'meshy' | 'tripo';
        baseURL?: string | null;
        submitPath?: string | null;
        statusPath?: string | null;
        apiKeyHint?: string | null;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  imageGeneration?: {
    defaultProvider?: ('gemini-official' | 'gemini-third-party') | null;
    timeoutSeconds?: number | null;
    official?: {
      baseURL?: string | null;
      model?: string | null;
      /**
       * Optional. If empty, runtime falls back to GEMINI_IMAGE_API_KEY.
       */
      apiKey?: string | null;
    };
    thirdParty?: {
      baseURL?: string | null;
      model?: string | null;
      /**
       * Optional. If empty, runtime falls back to GEMINI_IMAGE_THIRD_PARTY_API_KEY.
       */
      apiKey?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage non-sensitive Supabase Storage settings here. Runtime code reads bucket, prefix, baseURL, and signedDownloads from this global only. Supabase service keys must stay in environment variables.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage-settings".
 */
export interface StorageSetting {
  id: number;
  /**
   * Default: disabled. Turn this on only after Supabase bucket and environment secrets are configured.
   */
  enabled?: boolean | null;
  /**
   * Default: empty. Example: media-assets-prod.
   */
  bucket?: string | null;
  /**
   * Default: media. Files are stored under this logical folder prefix.
   */
  prefix?: string | null;
  /**
   * Default: empty. Optional Supabase Storage public object base URL used for media access URLs.
   */
  baseURL?: string | null;
  /**
   * Default: enabled. When disabled, absolute media URLs are returned without signing.
   */
  signedDownloads?: boolean | null;
  /**
   * Default: environment. This is an operator note only. Real secrets still live in environment variables.
   */
  credentialsSource?: string | null;
  /**
   * Optional operator timestamp for the last successful storage validation.
   */
  lastValidatedAt?: string | null;
  /**
   * Optional operator timestamp for the last key rotation event recorded outside Payload.
   */
  lastRotatedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage non-sensitive request origin and remote asset allowlists here. Runtime security checks prefer this global when values are present, then fall back to legacy environment allowlists for migration.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "security-settings".
 */
export interface SecuritySetting {
  id: number;
  /**
   * Default: empty. Add one absolute origin per row, for example https://app.example.com. Local development still allows requests without Origin outside production.
   */
  allowedMutationOrigins?:
    | {
        origin: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Default: empty. Add hostnames such as cdn.example.com or example.com. Subdomains are matched automatically.
   */
  allowedRemoteAssetHosts?:
    | {
        host: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage deployment-time database and app runtime variables. Secrets must still be stored in your hosting platform environment.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-deployment-settings".
 */
export interface RuntimeDeploymentSetting {
  id: number;
  databaseConnectionMode: 'aws-rds-fields' | 'database-url';
  /**
   * Paste the deployment DATABASE_URL template without the real password if you want. Supabase Postgres is the preferred production database.
   */
  databaseUrlTemplate?: string | null;
  awsRdsHost?: string | null;
  awsRdsPort?: number | null;
  awsRdsDbName?: string | null;
  awsRdsUsername?: string | null;
  awsRdsSslMode?: ('require' | 'verify-full' | 'disable') | null;
  awsRdsSslRejectUnauthorized?: boolean | null;
  /**
   * Optional operator notes such as current security group, public access status, or the production server IP to allow.
   */
  databaseSecurityChecklist?: string | null;
  nextPublicAppUrl?: string | null;
  /**
   * Optional note for operators about where the current PAYLOAD_SECRET lives and when it was rotated.
   */
  payloadSecretRotationNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  supportEmail?: T;
  announcement?: T;
  headerNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        aboutEyebrow?: T;
        aboutTitle?: T;
        aboutText?: T;
        directionEyebrow?: T;
        directionTitle?: T;
        directionText?: T;
      };
  paymentProviders?:
    | T
    | {
        subscriptionProvider?: T;
        orderProvider?: T;
        providerNotice?: T;
      };
  subscriptionPlans?:
    | T
    | {
        starter?:
          | T
          | {
              name?: T;
              shortLabel?: T;
              monthlyPrice?: T;
              creditsPerMonth?: T;
              description?: T;
              features?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
            };
        pro?:
          | T
          | {
              name?: T;
              shortLabel?: T;
              monthlyPrice?: T;
              creditsPerMonth?: T;
              description?: T;
              features?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
            };
        studio?:
          | T
          | {
              name?: T;
              shortLabel?: T;
              monthlyPrice?: T;
              creditsPerMonth?: T;
              description?: T;
              features?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
            };
      };
  generationPricing?:
    | T
    | {
        imageCredits?: T;
        textCredits?: T;
        hybridCredits?: T;
        downloadCredits?: T;
      };
  modelAccessPolicy?:
    | T
    | {
        chargePreviewCredits?: T;
        previewCredits?: T;
        chargeDownloadCredits?: T;
        downloadCredits?: T;
      };
  creditPackages?:
    | T
    | {
        title?: T;
        shopifyVariantId?: T;
        credits?: T;
        price?: T;
        currency?: T;
        id?: T;
      };
  emailSettings?:
    | T
    | {
        sender?:
          | T
          | {
              fromName?: T;
              fromAddress?: T;
              replyTo?: T;
            };
        branding?:
          | T
          | {
              productName?: T;
              footerText?: T;
            };
        templates?:
          | T
          | {
              welcome?:
                | T
                | {
                    subject?: T;
                    intro?: T;
                    ctaLabel?: T;
                  };
              verify?:
                | T
                | {
                    subject?: T;
                    intro?: T;
                    ctaLabel?: T;
                  };
              forgotPassword?:
                | T
                | {
                    subject?: T;
                    intro?: T;
                    ctaLabel?: T;
                  };
            };
        businessTemplates?:
          | T
          | {
              subscriptionSuccess?:
                | T
                | {
                    subject?: T;
                    intro?: T;
                    ctaLabel?: T;
                  };
              orderPaid?:
                | T
                | {
                    subject?: T;
                    intro?: T;
                    ctaLabel?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-content_select".
 */
export interface HomepageContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  introBand?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
      };
  featuredRail?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        searchLabel?: T;
        moreLabel?: T;
      };
  featuredWorks?:
    | T
    | {
        category?: T;
        title?: T;
        summary?: T;
        tone?: T;
        id?: T;
      };
  serviceIntro?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
      };
  collectionShelf?:
    | T
    | {
        title?: T;
        hotLabel?: T;
        newLabel?: T;
        moreLabel?: T;
        allLabel?: T;
      };
  serviceBlocks?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  useCases?:
    | T
    | {
        label?: T;
        id?: T;
      };
  processSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  processSteps?:
    | T
    | {
        step?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  entrySection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        text?: T;
      };
  faqSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-provider-settings_select".
 */
export interface AiProviderSettingsSelect<T extends boolean = true> {
  defaultProvider?: T;
  mockMode?: T;
  credentialsNotice?: T;
  polling?:
    | T
    | {
        enabled?: T;
        intervalSeconds?: T;
        timeoutMinutes?: T;
      };
  creditRules?:
    | T
    | {
        reserveOnSubmit?: T;
        refundOnFailure?: T;
      };
  meshy?:
    | T
    | {
        credentialsSource?: T;
        baseURL?: T;
        apiKeyMode?: T;
        apiKey?: T;
        textTo3DAiModel?: T;
        imageTo3DAiModel?: T;
        shouldTexture?: T;
        enablePBR?: T;
        hdTexture?: T;
        multiImageEnabled?: T;
        pricing?:
          | T
          | {
              textTo3DCredits?: T;
              imageTo3DCredits?: T;
              multiImageTo3DCredits?: T;
            };
        modelType?: T;
        topology?: T;
        targetPolycount?: T;
        targetFormats?: T;
        moderation?: T;
        imageEnhancement?: T;
        removeLighting?: T;
        lastValidatedAt?: T;
        lastRotatedAt?: T;
      };
  providers?:
    | T
    | {
        provider?: T;
        baseURL?: T;
        submitPath?: T;
        statusPath?: T;
        apiKeyHint?: T;
        enabled?: T;
        id?: T;
      };
  imageGeneration?:
    | T
    | {
        defaultProvider?: T;
        timeoutSeconds?: T;
        official?:
          | T
          | {
              baseURL?: T;
              model?: T;
              apiKey?: T;
            };
        thirdParty?:
          | T
          | {
              baseURL?: T;
              model?: T;
              apiKey?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage-settings_select".
 */
export interface StorageSettingsSelect<T extends boolean = true> {
  enabled?: T;
  bucket?: T;
  prefix?: T;
  baseURL?: T;
  signedDownloads?: T;
  credentialsSource?: T;
  lastValidatedAt?: T;
  lastRotatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "security-settings_select".
 */
export interface SecuritySettingsSelect<T extends boolean = true> {
  allowedMutationOrigins?:
    | T
    | {
        origin?: T;
        id?: T;
      };
  allowedRemoteAssetHosts?:
    | T
    | {
        host?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-deployment-settings_select".
 */
export interface RuntimeDeploymentSettingsSelect<T extends boolean = true> {
  databaseConnectionMode?: T;
  databaseUrlTemplate?: T;
  awsRdsHost?: T;
  awsRdsPort?: T;
  awsRdsDbName?: T;
  awsRdsUsername?: T;
  awsRdsSslMode?: T;
  awsRdsSslRejectUnauthorized?: T;
  databaseSecurityChecklist?: T;
  nextPublicAppUrl?: T;
  payloadSecretRotationNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}